<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<OutputType>Library</OutputType>
		<RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
		<RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
		<EnableNETAnalyzers>false</EnableNETAnalyzers>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DocumentationFile>IOWebApplication.Core.xml</DocumentationFile>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="IO.RegixClient" Version="8.0.5" />
		<PackageReference Include="Mapster" Version="7.4.0" />
		<PackageReference Include="Mapster.Core" Version="1.2.1" />
		<PackageReference Include="NetBarcode" Version="1.7.1.1" />
		<!--<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.9.2" />-->
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />
		<PackageReference Include="NPOI" Version="2.5.6" />
		<PackageReference Include="QRCoder-ImageSharp" Version="0.10.0" />
		<!--<PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="8.0.7" />-->
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="SSH.NET" Version="2025.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.3.9" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\IOWebApplication.Infrastructure\IOWebApplication.Infrastructure.csproj" />
		<ProjectReference Include="..\Proxy.V2T.Core\Proxy.V2T.Core.csproj" />
	</ItemGroup>
	
</Project>