<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Views\FastProcessSelectionCourt\Preview.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\Shared\CreatePdf.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\Shared\DisplayTemplates\objInline.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="IO.HtmlToPdf" Version="6.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.16" />
    <PackageReference Include="Microsoft.DotNet.PlatformAbstractions" Version="3.1.6" />
    <PackageReference Include="Quartz.AspNetCore" Version="3.11.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
    <PackageReference Include="Razor.Templating.Core" Version="2.1.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\IOWebApplication.Core\IOWebApplication.Core.csproj" />
    <ProjectReference Include="..\IOWebApplication.Infrastructure\IOWebApplication.Infrastructure.csproj" />
    <ProjectReference Include="..\IOWebApplicationService.Infrastructure\IOWebApplicationService.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Certificates\Bank\bank-eiss">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Certificates\Epep\eiss_2025.p12">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Certificates\Epep\eiss_webrand.justice.bg.pfx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Certificates\Epep\epepCert2021.p12">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Certificates\Ispn\OKRAZHENSAD-GR.VARNA.p12">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Fonts\times.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Fonts\timesbd.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Fonts\timesbi.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Fonts\timesi.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Certificates\Bank\" />
  </ItemGroup>
</Project>