//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOWebApplication.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IOWebApplication.Resources.Controllers.AccountController", typeof(AccountController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. Администратор.
        /// </summary>
        public static string ADMIN {
            get {
                return ResourceManager.GetString("ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.3. Архивиране.
        /// </summary>
        public static string CASE_ARH {
            get {
                return ResourceManager.GetString("CASE_ARH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.2. Управление на дела.
        /// </summary>
        public static string CASE_EDIT {
            get {
                return ResourceManager.GetString("CASE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.1. Разпределение.
        /// </summary>
        public static string CASE_INIT {
            get {
                return ResourceManager.GetString("CASE_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.4. Призоваване.
        /// </summary>
        public static string DEL_USER {
            get {
                return ResourceManager.GetString("DEL_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Деловодство.
        /// </summary>
        public static string DOC_EDIT {
            get {
                return ResourceManager.GetString("DOC_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Регистратура.
        /// </summary>
        public static string DOC_INIT {
            get {
                return ResourceManager.GetString("DOC_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. Администратор на инфраструктура.
        /// </summary>
        public static string GLOBAL_ADMIN {
            get {
                return ResourceManager.GetString("GLOBAL_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.2. Управление на магистрати и служители.
        /// </summary>
        public static string HR_ADMIN {
            get {
                return ResourceManager.GetString("HR_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Счетоводство.
        /// </summary>
        public static string MONEY {
            get {
                return ResourceManager.GetString("MONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.1. Супервайзор на структура.
        /// </summary>
        public static string POWER_USER {
            get {
                return ResourceManager.GetString("POWER_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. Ограничен достъп.
        /// </summary>
        public static string RESTR {
            get {
                return ResourceManager.GetString("RESTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Статистика.
        /// </summary>
        public static string STAT {
            get {
                return ResourceManager.GetString("STAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Супервайзор.
        /// </summary>
        public static string SUPER {
            get {
                return ResourceManager.GetString("SUPER", resourceCulture);
            }
        }
    }
}
