//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOWebApplication.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NomenclatureController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NomenclatureController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IOWebApplication.Resources.Controllers.NomenclatureController", typeof(NomenclatureController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шифри по дело.
        /// </summary>
        public static string CaseCharacter {
            get {
                return ResourceManager.GetString("CaseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основен вид дела.
        /// </summary>
        public static string CaseGroup {
            get {
                return ResourceManager.GetString("CaseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статуси на дело.
        /// </summary>
        public static string CaseState {
            get {
                return ResourceManager.GetString("CaseState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точен вид дела.
        /// </summary>
        public static string CaseType {
            get {
                return ResourceManager.GetString("CaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Демо номенклатура.
        /// </summary>
        public static string DemoNomenclature {
            get {
                return ResourceManager.GetString("DemoNomenclature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ниво на съд.
        /// </summary>
        public static string DepartmentType {
            get {
                return ResourceManager.GetString("DepartmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основен вид документи.
        /// </summary>
        public static string DocumentGroup {
            get {
                return ResourceManager.GetString("DocumentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точен вид документи.
        /// </summary>
        public static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметри за бланки.
        /// </summary>
        public static string HtmlTemplateParam {
            get {
                return ResourceManager.GetString("HtmlTemplateParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид на Бланки.
        /// </summary>
        public static string HtmlTemplateType {
            get {
                return ResourceManager.GetString("HtmlTemplateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Институция/съдебно лице.
        /// </summary>
        public static string Institution {
            get {
                return ResourceManager.GetString("Institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид институция/съдебно лице.
        /// </summary>
        public static string InstitutionType {
            get {
                return ResourceManager.GetString("InstitutionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид известие.
        /// </summary>
        public static string NotificationType {
            get {
                return ResourceManager.GetString("NotificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ред на разглеждане на дело.
        /// </summary>
        public static string ProcessPriority {
            get {
                return ResourceManager.GetString("ProcessPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестова номенклатура.
        /// </summary>
        public static string TestNomenclature {
            get {
                return ResourceManager.GetString("TestNomenclature", resourceCulture);
            }
        }
    }
}
