//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
///Регистър БУЛСТАТ\Справка за номенклатурите на регистър БУЛСТАТ
namespace IOWebApplication.Infrastructure.Models.Regix.FetchNomenclatures
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/StateOfPlayService")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.bulstat.bg/StateOfPlayService", IsNullable = false)]
    public partial class FetchNomenclatures
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/Nomenclatures")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.bulstat.bg/Nomenclatures", IsNullable = false)]
    public partial class Nomenclatures
    {

        private CountryMultilangNomElement[] countryNomElementField;

        private SimpleNomenclature[] simpleNomenclatureField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CountryNomElement")]
        public CountryMultilangNomElement[] CountryNomElement
        {
            get
            {
                return this.countryNomElementField;
            }
            set
            {
                this.countryNomElementField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SimpleNomenclature")]
        public SimpleNomenclature[] SimpleNomenclature
        {
            get
            {
                return this.simpleNomenclatureField;
            }
            set
            {
                this.simpleNomenclatureField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/Nomenclatures")]
    public partial class CountryMultilangNomElement : MultilangNomElement
    {

        private string iSO2Field;

        private string iSO3Field;

        /// <remarks/>
        public string ISO2
        {
            get
            {
                return this.iSO2Field;
            }
            set
            {
                this.iSO2Field = value;
            }
        }

        /// <remarks/>
        public string ISO3
        {
            get
            {
                return this.iSO3Field;
            }
            set
            {
                this.iSO3Field = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CountryMultilangNomElement))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/Nomenclatures")]
    public partial class MultilangNomElement : NomenclatureEntry
    {

        private string nameBGField;

        private string nameENField;

        private int orderingField;

        private bool activeField;

        public MultilangNomElement()
        {
            this.orderingField = 0;
        }

        /// <remarks/>
        public string NameBG
        {
            get
            {
                return this.nameBGField;
            }
            set
            {
                this.nameBGField = value;
            }
        }

        /// <remarks/>
        public string NameEN
        {
            get
            {
                return this.nameENField;
            }
            set
            {
                this.nameENField = value;
            }
        }

        /// <remarks/>
        public int Ordering
        {
            get
            {
                return this.orderingField;
            }
            set
            {
                this.orderingField = value;
            }
        }

        /// <remarks/>
        public bool Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultilangNomElement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CountryMultilangNomElement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NomenclatureElement))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/NomenclatureEntry")]
    public partial class NomenclatureEntry
    {

        private string codeField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/NomenclatureElement")]
    public partial class NomenclatureElement : NomenclatureEntry
    {

        private string nameField;

        private int orderingField;

        private bool activeField;

        public NomenclatureElement()
        {
            this.orderingField = 0;
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public int Ordering
        {
            get
            {
                return this.orderingField;
            }
            set
            {
                this.orderingField = value;
            }
        }

        /// <remarks/>
        public bool Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/Nomenclatures")]
    public partial class SimpleNomenclature
    {

        private MetaDefinition definitionField;

        private MultilangNomElement[] nomElementField;

        /// <remarks/>
        public MetaDefinition Definition
        {
            get
            {
                return this.definitionField;
            }
            set
            {
                this.definitionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NomElement")]
        public MultilangNomElement[] NomElement
        {
            get
            {
                return this.nomElementField;
            }
            set
            {
                this.nomElementField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/MetaDefinition")]
    public partial class MetaDefinition
    {

        private string codeField;

        private string nameField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
}
