//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
//Търговски регистър\Справка за актуално състояние за всички вписани обстоятелства по раздели(v3)
namespace IOWebApplication.Infrastructure.Models.Regix.GetActualStateV3
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/AV/TR/ActualStateRequestV3")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://egov.bg/RegiX/AV/TR/ActualStateRequestV3", IsNullable = false)]
    public partial class ActualStateRequestV3
    {

        private string uICField;

        private string fieldListField;

        /// <remarks/>
        public string UIC
        {
            get
            {
                return this.uICField;
            }
            set
            {
                this.uICField = value;
            }
        }

        /// <remarks/>
        public string FieldList
        {
            get
            {
                return this.fieldListField;
            }
            set
            {
                this.fieldListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/AV/TR/ActualStateResponseV3")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://egov.bg/RegiX/AV/TR/ActualStateResponseV3", IsNullable = false)]
    public partial class ActualStateResponseV3
    {

        private DeedType deedField;

        private System.DateTime dataValidForDateField;

        private bool dataValidForDateFieldSpecified;

        private bool dataFoundField;

        private bool dataFoundFieldSpecified;

        /// <remarks/>
        public DeedType Deed
        {
            get
            {
                return this.deedField;
            }
            set
            {
                this.deedField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DataValidForDate
        {
            get
            {
                return this.dataValidForDateField;
            }
            set
            {
                this.dataValidForDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataValidForDateSpecified
        {
            get
            {
                return this.dataValidForDateFieldSpecified;
            }
            set
            {
                this.dataValidForDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool DataFound
        {
            get
            {
                return this.dataFoundField;
            }
            set
            {
                this.dataFoundField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataFoundSpecified
        {
            get
            {
                return this.dataFoundFieldSpecified;
            }
            set
            {
                this.dataFoundFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/AV/TR/SubdeedsCommon")]
    public partial class DeedType
    {

        private DeedStatusType deedStatusField;

        private string companyNameField;

        private string gUIDField;

        private string uICField;

        private LegalFormType legalFormField;

        private string caseNoField;

        private string caseYearField;

        private string courtNoField;

        private LiquidationOrInsolvency liquidationOrInsolvencyField;

        private bool liquidationOrInsolvencyFieldSpecified;

        private Subdeeds subdeedsField;

        /// <remarks/>
        public DeedStatusType DeedStatus
        {
            get
            {
                return this.deedStatusField;
            }
            set
            {
                this.deedStatusField = value;
            }
        }

        /// <remarks/>
        public string CompanyName
        {
            get
            {
                return this.companyNameField;
            }
            set
            {
                this.companyNameField = value;
            }
        }

        /// <remarks/>
        public string GUID
        {
            get
            {
                return this.gUIDField;
            }
            set
            {
                this.gUIDField = value;
            }
        }

        /// <remarks/>
        public string UIC
        {
            get
            {
                return this.uICField;
            }
            set
            {
                this.uICField = value;
            }
        }

        /// <remarks/>
        public LegalFormType LegalForm
        {
            get
            {
                return this.legalFormField;
            }
            set
            {
                this.legalFormField = value;
            }
        }

        /// <remarks/>
        public string CaseNo
        {
            get
            {
                return this.caseNoField;
            }
            set
            {
                this.caseNoField = value;
            }
        }

        /// <remarks/>
        public string CaseYear
        {
            get
            {
                return this.caseYearField;
            }
            set
            {
                this.caseYearField = value;
            }
        }

        /// <remarks/>
        public string CourtNo
        {
            get
            {
                return this.courtNoField;
            }
            set
            {
                this.courtNoField = value;
            }
        }

        /// <remarks/>
        public LiquidationOrInsolvency LiquidationOrInsolvency
        {
            get
            {
                return this.liquidationOrInsolvencyField;
            }
            set
            {
                this.liquidationOrInsolvencyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LiquidationOrInsolvencySpecified
        {
            get
            {
                return this.liquidationOrInsolvencyFieldSpecified;
            }
            set
            {
                this.liquidationOrInsolvencyFieldSpecified = value;
            }
        }

        /// <remarks/>
        public Subdeeds Subdeeds
        {
            get
            {
                return this.subdeedsField;
            }
            set
            {
                this.subdeedsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/AV/TR/SubdeedsCommon")]
    public enum DeedStatusType
    {

        /// <remarks/>
        N,

        /// <remarks/>
        E,

        /// <remarks/>
        C,

        /// <remarks/>
        L,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/AV/TR/SubdeedsCommon")]
    public enum LegalFormType
    {

        /// <remarks/>
        ЕТ,

        /// <remarks/>
        СД,

        /// <remarks/>
        КД,

        /// <remarks/>
        ООД,

        /// <remarks/>
        АД,

        /// <remarks/>
        КДА,

        /// <remarks/>
        Кооперация,

        /// <remarks/>
        КЧТ,

        /// <remarks/>
        ТПП,

        /// <remarks/>
        ЕООД,

        /// <remarks/>
        ЕАД,

        /// <remarks/>
        АДСИЦ,

        /// <remarks/>
        ДП,

        /// <remarks/>
        ОП,

        /// <remarks/>
        ЕАДСИЦ,

        /// <remarks/>
        ЕОИИ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Поделение на ЕОИИ")]
        ПоделениенаЕОИИ,

        /// <remarks/>
        ЕД,

        /// <remarks/>
        ЕКД,

        /// <remarks/>
        ЕКДОО,

        /// <remarks/>
        ЧДПР,

        /// <remarks/>
        ЧЮЛ,

        /// <remarks/>
        ЧФЛ,

        /// <remarks/>
        Сдружение,

        /// <remarks/>
        Фондация,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Клон на ЧЮЛНЦ")]
        КлоннаЧЮЛНЦ,

        /// <remarks/>
        НЧ,

        /// <remarks/>
        Неизвестно,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/AV/TR/SubdeedsCommon")]
    public enum LiquidationOrInsolvency
    {

        /// <remarks/>
        Liquidation,

        /// <remarks/>
        Insolvency,

        /// <remarks/>
        InsolvencySecIns,

        /// <remarks/>
        InsolvencyThirdIns,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/AV/TR/SubdeedsCommon")]
    public partial class Subdeeds
    {

        private Subdeed[] subdeedField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Subdeed")]
        public Subdeed[] Subdeed
        {
            get
            {
                return this.subdeedField;
            }
            set
            {
                this.subdeedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/AV/TR/SubdeedsCommon")]
    public partial class Subdeed
    {

        private Record[] recordsField;

        private string subUICField;

        private SubUICType subUICTypeField;

        private bool subUICTypeFieldSpecified;

        private SubdeedStatusType subdeedStatusField;

        private bool subdeedStatusFieldSpecified;

        private string subUICNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Record[] Records
        {
            get
            {
                return this.recordsField;
            }
            set
            {
                this.recordsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubUIC
        {
            get
            {
                return this.subUICField;
            }
            set
            {
                this.subUICField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SubUICType SubUICType
        {
            get
            {
                return this.subUICTypeField;
            }
            set
            {
                this.subUICTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SubUICTypeSpecified
        {
            get
            {
                return this.subUICTypeFieldSpecified;
            }
            set
            {
                this.subUICTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SubdeedStatusType SubdeedStatus
        {
            get
            {
                return this.subdeedStatusField;
            }
            set
            {
                this.subdeedStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SubdeedStatusSpecified
        {
            get
            {
                return this.subdeedStatusFieldSpecified;
            }
            set
            {
                this.subdeedStatusFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubUICName
        {
            get
            {
                return this.subUICNameField;
            }
            set
            {
                this.subUICNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/AV/TR/SubdeedsCommon")]
    public partial class Record
    {

        private object recordDataField;

        private int recordIdField;

        private int incomingIdField;

        private string fieldIdentField;

        private Field mainFieldField;

        private string fieldEntryNumberField;

        private System.DateTime fieldActionDateField;

        /// <remarks/>
        public object RecordData
        {
            get
            {
                return this.recordDataField;
            }
            set
            {
                this.recordDataField = value;
            }
        }

        /// <remarks/>
        public int RecordId
        {
            get
            {
                return this.recordIdField;
            }
            set
            {
                this.recordIdField = value;
            }
        }

        /// <remarks/>
        public int IncomingId
        {
            get
            {
                return this.incomingIdField;
            }
            set
            {
                this.incomingIdField = value;
            }
        }

        /// <remarks/>
        public string FieldIdent
        {
            get
            {
                return this.fieldIdentField;
            }
            set
            {
                this.fieldIdentField = value;
            }
        }

        /// <remarks/>
        public Field MainField
        {
            get
            {
                return this.mainFieldField;
            }
            set
            {
                this.mainFieldField = value;
            }
        }

        /// <remarks/>
        public string FieldEntryNumber
        {
            get
            {
                return this.fieldEntryNumberField;
            }
            set
            {
                this.fieldEntryNumberField = value;
            }
        }

        /// <remarks/>
        public System.DateTime FieldActionDate
        {
            get
            {
                return this.fieldActionDateField;
            }
            set
            {
                this.fieldActionDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/AV/TR/SubdeedsCommon")]
    public partial class Field
    {

        private int groupIdField;

        private bool groupIdFieldSpecified;

        private string groupNameField;

        private int sectionIdField;

        private bool sectionIdFieldSpecified;

        private string sectionNameField;

        private string mainFieldIdentField;

        private string mainFieldCodeField;

        private string mainFieldNameField;

        /// <remarks/>
        public int GroupId
        {
            get
            {
                return this.groupIdField;
            }
            set
            {
                this.groupIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GroupIdSpecified
        {
            get
            {
                return this.groupIdFieldSpecified;
            }
            set
            {
                this.groupIdFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string GroupName
        {
            get
            {
                return this.groupNameField;
            }
            set
            {
                this.groupNameField = value;
            }
        }

        /// <remarks/>
        public int SectionId
        {
            get
            {
                return this.sectionIdField;
            }
            set
            {
                this.sectionIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SectionIdSpecified
        {
            get
            {
                return this.sectionIdFieldSpecified;
            }
            set
            {
                this.sectionIdFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string SectionName
        {
            get
            {
                return this.sectionNameField;
            }
            set
            {
                this.sectionNameField = value;
            }
        }

        /// <remarks/>
        public string MainFieldIdent
        {
            get
            {
                return this.mainFieldIdentField;
            }
            set
            {
                this.mainFieldIdentField = value;
            }
        }

        /// <remarks/>
        public string MainFieldCode
        {
            get
            {
                return this.mainFieldCodeField;
            }
            set
            {
                this.mainFieldCodeField = value;
            }
        }

        /// <remarks/>
        public string MainFieldName
        {
            get
            {
                return this.mainFieldNameField;
            }
            set
            {
                this.mainFieldNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/AV/TR/SubdeedsCommon")]
    public enum SubUICType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("500")]
        Item500,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/AV/TR/SubdeedsCommon")]
    public enum SubdeedStatusType
    {

        /// <remarks/>
        A,

        /// <remarks/>
        C,
    }
}
