//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
//Регистър на уведомленията за трудовите договори и уведомления за промяна на работодател\Справка за актуално състояние на всички/действащите трудови договори
namespace IOWebApplication.Infrastructure.Models.Regix.GetEmploymentContracts
{
    using System.ComponentModel.DataAnnotations;
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/NRA/EmploymentContracts")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://egov.bg/RegiX/NRA/EmploymentContracts", IsNullable = false)]
    public enum ContractsFilterType
    {

        /// <remarks/>
        All,

        /// <remarks/>
        Active,

        /// <remarks/>
        Terminated,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/NRA/EmploymentContracts")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://egov.bg/RegiX/NRA/EmploymentContracts", IsNullable = false)]
    public enum EikTypeType
    {

        /// <remarks/>
        Bulstat,

        /// <remarks/>
        EGN,

        /// <remarks/>
        LNC,

        /// <remarks/>
        SystemNo,

        /// <remarks/>
        BulstatCL,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/NRA/EmploymentContracts/Request")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://egov.bg/RegiX/NRA/EmploymentContracts/Request", IsNullable = false)]
    public partial class EmploymentContractsRequest
    {

        private IdentityTypeRequest identityField;

        private ContractsFilterType contractsFilterField;

        private bool contractsFilterFieldSpecified;

        private System.DateTime dateToField;

        private bool dateToFieldSpecified;

        private int pageField;

        private bool pageFieldSpecified;

        private int sizeField;

        private bool sizeFieldSpecified;

        /// <remarks/>
        public IdentityTypeRequest Identity
        {
            get
            {
                return this.identityField;
            }
            set
            {
                this.identityField = value;
            }
        }

        /// <remarks/>
        public ContractsFilterType ContractsFilter
        {
            get
            {
                return this.contractsFilterField;
            }
            set
            {
                this.contractsFilterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContractsFilterSpecified
        {
            get
            {
                return this.contractsFilterFieldSpecified;
            }
            set
            {
                this.contractsFilterFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DateTo
        {
            get
            {
                return this.dateToField;
            }
            set
            {
                this.dateToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateToSpecified
        {
            get
            {
                return this.dateToFieldSpecified;
            }
            set
            {
                this.dateToFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int Page
        {
            get
            {
                return this.pageField;
            }
            set
            {
                this.pageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PageSpecified
        {
            get
            {
                return this.pageFieldSpecified;
            }
            set
            {
                this.pageFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int Size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SizeSpecified
        {
            get
            {
                return this.sizeFieldSpecified;
            }
            set
            {
                this.sizeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/NRA/EmploymentContracts/Request")]
    public partial class IdentityTypeRequest
    {

        private string idField;

        private EikTypeType tYPEField;

        /// <remarks/>
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public EikTypeType TYPE
        {
            get
            {
                return this.tYPEField;
            }
            set
            {
                this.tYPEField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://egov.bg/RegiX/NRA/EmploymentContracts/Response")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://egov.bg/RegiX/NRA/EmploymentContracts/Response", IsNullable = false)]
    public partial class EmploymentContractsResponse
    {

        private ResponseIdentityType identityField;

        private EContract[] eContractsField;

        private StatusType statusField;

        private ContractsFilterType contractsFilterField;

        private bool contractsFilterFieldSpecified;

        private System.DateTime reportDateField;

        private bool reportDateFieldSpecified;

        private System.DateTime dateToField;

        private bool dateToFieldSpecified;

        private int pageField;

        private bool pageFieldSpecified;

        private int sizeField;

        private bool sizeFieldSpecified;

        /// <remarks/>
        public ResponseIdentityType Identity
        {
            get
            {
                return this.identityField;
            }
            set
            {
                this.identityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://egov.bg/RegiX/NRA/EmploymentContracts", IsNullable = false)]
        public EContract[] EContracts
        {
            get
            {
                return this.eContractsField;
            }
            set
            {
                this.eContractsField = value;
            }
        }

        /// <remarks/>
        public StatusType Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public ContractsFilterType ContractsFilter
        {
            get
            {
                return this.contractsFilterField;
            }
            set
            {
                this.contractsFilterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContractsFilterSpecified
        {
            get
            {
                return this.contractsFilterFieldSpecified;
            }
            set
            {
                this.contractsFilterFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime ReportDate
        {
            get
            {
                return this.reportDateField;
            }
            set
            {
                this.reportDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReportDateSpecified
        {
            get
            {
                return this.reportDateFieldSpecified;
            }
            set
            {
                this.reportDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DateTo
        {
            get
            {
                return this.dateToField;
            }
            set
            {
                this.dateToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateToSpecified
        {
            get
            {
                return this.dateToFieldSpecified;
            }
            set
            {
                this.dateToFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int Page
        {
            get
            {
                return this.pageField;
            }
            set
            {
                this.pageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PageSpecified
        {
            get
            {
                return this.pageFieldSpecified;
            }
            set
            {
                this.pageFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int Size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SizeSpecified
        {
            get
            {
                return this.sizeFieldSpecified;
            }
            set
            {
                this.sizeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/NRA/EmploymentContracts")]
    public partial class ResponseIdentityType
    {

        private string idField;

        private EikTypeType tYPEField;

        private bool tYPEFieldSpecified;

        /// <remarks/>
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public EikTypeType TYPE
        {
            get
            {
                return this.tYPEField;
            }
            set
            {
                this.tYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TYPESpecified
        {
            get
            {
                return this.tYPEFieldSpecified;
            }
            set
            {
                this.tYPEFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/NRA/EmploymentContracts")]
    public partial class EContract
    {

        private string contractorBulstatField;

        private string contractorNameField;

        private string individualEIKField;

        private string individualNamesField;

        private System.DateTime startDateField;

        private bool startDateFieldSpecified;

        private System.DateTime lastAmendDateField;

        private bool lastAmendDateFieldSpecified;

        private System.DateTime endDateField;

        private bool endDateFieldSpecified;

        private string reasonField;

        private System.DateTime timeLimitField;

        private bool timeLimitFieldSpecified;

        private string ecoCodeField;

        private string professionCodeField;

        private decimal remunerationField;

        private bool remunerationFieldSpecified;

        private string professionNameField;

        private string eKATTECodeField;

        private string lastTermIdField;

        private System.DateTime beginDateField;

        private bool beginDateFieldSpecified;

        private System.DateTime beginAmendmentDateField;

        private bool beginAmendmentDateFieldSpecified;

        private decimal salaryEuroField;

        private bool salaryEuroFieldSpecified;

        /// <remarks/>
        public string ContractorBulstat
        {
            get
            {
                return this.contractorBulstatField;
            }
            set
            {
                this.contractorBulstatField = value;
            }
        }

        /// <remarks/>
        public string ContractorName
        {
            get
            {
                return this.contractorNameField;
            }
            set
            {
                this.contractorNameField = value;
            }
        }

        /// <remarks/>
        public string IndividualEIK
        {
            get
            {
                return this.individualEIKField;
            }
            set
            {
                this.individualEIKField = value;
            }
        }

        /// <remarks/>
        public string IndividualNames
        {
            get
            {
                return this.individualNamesField;
            }
            set
            {
                this.individualNamesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateSpecified
        {
            get
            {
                return this.startDateFieldSpecified;
            }
            set
            {
                this.startDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime LastAmendDate
        {
            get
            {
                return this.lastAmendDateField;
            }
            set
            {
                this.lastAmendDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastAmendDateSpecified
        {
            get
            {
                return this.lastAmendDateFieldSpecified;
            }
            set
            {
                this.lastAmendDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndDateSpecified
        {
            get
            {
                return this.endDateFieldSpecified;
            }
            set
            {
                this.endDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime TimeLimit
        {
            get
            {
                return this.timeLimitField;
            }
            set
            {
                this.timeLimitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimeLimitSpecified
        {
            get
            {
                return this.timeLimitFieldSpecified;
            }
            set
            {
                this.timeLimitFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string EcoCode
        {
            get
            {
                return this.ecoCodeField;
            }
            set
            {
                this.ecoCodeField = value;
            }
        }

        /// <remarks/>
        public string ProfessionCode
        {
            get
            {
                return this.professionCodeField;
            }
            set
            {
                this.professionCodeField = value;
            }
        }

        /// <remarks/>
        public decimal Remuneration
        {
            get
            {
                return this.remunerationField;
            }
            set
            {
                this.remunerationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RemunerationSpecified
        {
            get
            {
                return this.remunerationFieldSpecified;
            }
            set
            {
                this.remunerationFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string ProfessionName
        {
            get
            {
                return this.professionNameField;
            }
            set
            {
                this.professionNameField = value;
            }
        }

        /// <remarks/>
        public string EKATTECode
        {
            get
            {
                return this.eKATTECodeField;
            }
            set
            {
                this.eKATTECodeField = value;
            }
        }

        /// <remarks/>
        public string LastTermId
        {
            get
            {
                return this.lastTermIdField;
            }
            set
            {
                this.lastTermIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime BeginDate
        {
            get
            {
                return this.beginDateField;
            }
            set
            {
                this.beginDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BeginDateSpecified
        {
            get
            {
                return this.beginDateFieldSpecified;
            }
            set
            {
                this.beginDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime BeginAmendmentDate
        {
            get
            {
                return this.beginAmendmentDateField;
            }
            set
            {
                this.beginAmendmentDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BeginAmendmentDateSpecified
        {
            get
            {
                return this.beginAmendmentDateFieldSpecified;
            }
            set
            {
                this.beginAmendmentDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal SalaryEuro
        {
            get
            {
                return this.salaryEuroField;
            }
            set
            {
                this.salaryEuroField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalaryEuroSpecified
        {
            get
            {
                return this.salaryEuroFieldSpecified;
            }
            set
            {
                this.salaryEuroFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/NRA/EmploymentContracts")]
    public partial class StatusType
    {

        private int codeField;

        private bool codeFieldSpecified;

        private string messageField;

        /// <remarks/>
        public int Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodeSpecified
        {
            get
            {
                return this.codeFieldSpecified;
            }
            set
            {
                this.codeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
}
