//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
//Справка за лице по документ за самоличност-V2
namespace IOWebApplication.Infrastructure.Models.Regix.GetPersonalIdentityV2
{
    using System.Xml.Serialization;

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoRequest")]
    [System.Xml.Serialization.XmlRootAttribute("PersonalIdentityInfoRequest", Namespace = "http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoRequest", IsNullable = false)]
    public partial class PersonalIdentityInfoRequestType
    {

        private string identityDocumentNumberField;

        private string eGNField;

        /// <remarks/>
        public string IdentityDocumentNumber
        {
            get
            {
                return this.identityDocumentNumberField;
            }
            set
            {
                this.identityDocumentNumberField = value;
            }
        }

        /// <remarks/>
        public string EGN
        {
            get
            {
                return this.eGNField;
            }
            set
            {
                this.eGNField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse")]
    [System.Xml.Serialization.XmlRootAttribute("PersonalIdentityInfoResponse", Namespace = "http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse", IsNullable = false)]
    public partial class PersonalIdentityInfoResponseType
    {

        private ReturnInformation returnInformationsField;

        private string eGNField;

        private PersonNames personNamesField;

        private DLCategory[] dLCategоriesField;

        private string dLCommonRestrictionsField;

        private ForeignCitizenType dataForeignCitizenField;

        private string[] rPRemarksField;

        private string rPTypeofPermitField;

        private string documentTypeField;

        private string documentTypeLatinField;

        private string documentActualStatusField;

        private System.DateTime actualStatusDateField;

        private bool actualStatusDateFieldSpecified;

        private string documentStatusReasonField;

        private string identityDocumentNumberField;

        private System.DateTime issueDateField;

        private bool issueDateFieldSpecified;

        private string issuerPlaceField;

        private string issuerPlaceLatinField;

        private string issuerNameField;

        private string issuerNameLatinField;

        private System.DateTime validDateField;

        private bool validDateFieldSpecified;

        private System.DateTime birthDateField;

        private bool birthDateFieldSpecified;

        private BirthPlace birthPlaceField;

        private string genderNameField;

        private string genderNameLatinField;

        private Nationality[] nationalityListField;

        private PermanentAddress permanentAddressField;

        private double heightField;

        private bool heightFieldSpecified;

        private string eyesColorField;

        private byte[] pictureField;

        private byte[] identitySignatureField;

        /// <remarks/>
        public ReturnInformation ReturnInformations
        {
            get
            {
                return this.returnInformationsField;
            }
            set
            {
                this.returnInformationsField = value;
            }
        }

        /// <remarks/>
        public string EGN
        {
            get
            {
                return this.eGNField;
            }
            set
            {
                this.eGNField = value;
            }
        }

        /// <remarks/>
        public PersonNames PersonNames
        {
            get
            {
                return this.personNamesField;
            }
            set
            {
                this.personNamesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public DLCategory[] DLCategоries
        {
            get
            {
                return this.dLCategоriesField;
            }
            set
            {
                this.dLCategоriesField = value;
            }
        }

        /// <remarks/>
        public string DLCommonRestrictions
        {
            get
            {
                return this.dLCommonRestrictionsField;
            }
            set
            {
                this.dLCommonRestrictionsField = value;
            }
        }

        /// <remarks/>
        public ForeignCitizenType DataForeignCitizen
        {
            get
            {
                return this.dataForeignCitizenField;
            }
            set
            {
                this.dataForeignCitizenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RPRemark", IsNullable = false)]
        public string[] RPRemarks
        {
            get
            {
                return this.rPRemarksField;
            }
            set
            {
                this.rPRemarksField = value;
            }
        }

        /// <remarks/>
        public string RPTypeofPermit
        {
            get
            {
                return this.rPTypeofPermitField;
            }
            set
            {
                this.rPTypeofPermitField = value;
            }
        }

        /// <remarks/>
        public string DocumentType
        {
            get
            {
                return this.documentTypeField;
            }
            set
            {
                this.documentTypeField = value;
            }
        }

        /// <remarks/>
        public string DocumentTypeLatin
        {
            get
            {
                return this.documentTypeLatinField;
            }
            set
            {
                this.documentTypeLatinField = value;
            }
        }

        /// <remarks/>
        public string DocumentActualStatus
        {
            get
            {
                return this.documentActualStatusField;
            }
            set
            {
                this.documentActualStatusField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ActualStatusDate
        {
            get
            {
                return this.actualStatusDateField;
            }
            set
            {
                this.actualStatusDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActualStatusDateSpecified
        {
            get
            {
                return this.actualStatusDateFieldSpecified;
            }
            set
            {
                this.actualStatusDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string DocumentStatusReason
        {
            get
            {
                return this.documentStatusReasonField;
            }
            set
            {
                this.documentStatusReasonField = value;
            }
        }

        /// <remarks/>
        public string IdentityDocumentNumber
        {
            get
            {
                return this.identityDocumentNumberField;
            }
            set
            {
                this.identityDocumentNumberField = value;
            }
        }

        /// <remarks/>
        public System.DateTime IssueDate
        {
            get
            {
                return this.issueDateField;
            }
            set
            {
                this.issueDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IssueDateSpecified
        {
            get
            {
                return this.issueDateFieldSpecified;
            }
            set
            {
                this.issueDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string IssuerPlace
        {
            get
            {
                return this.issuerPlaceField;
            }
            set
            {
                this.issuerPlaceField = value;
            }
        }

        /// <remarks/>
        public string IssuerPlaceLatin
        {
            get
            {
                return this.issuerPlaceLatinField;
            }
            set
            {
                this.issuerPlaceLatinField = value;
            }
        }

        /// <remarks/>
        public string IssuerName
        {
            get
            {
                return this.issuerNameField;
            }
            set
            {
                this.issuerNameField = value;
            }
        }

        /// <remarks/>
        public string IssuerNameLatin
        {
            get
            {
                return this.issuerNameLatinField;
            }
            set
            {
                this.issuerNameLatinField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ValidDate
        {
            get
            {
                return this.validDateField;
            }
            set
            {
                this.validDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidDateSpecified
        {
            get
            {
                return this.validDateFieldSpecified;
            }
            set
            {
                this.validDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime BirthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BirthDateSpecified
        {
            get
            {
                return this.birthDateFieldSpecified;
            }
            set
            {
                this.birthDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public BirthPlace BirthPlace
        {
            get
            {
                return this.birthPlaceField;
            }
            set
            {
                this.birthPlaceField = value;
            }
        }

        /// <remarks/>
        public string GenderName
        {
            get
            {
                return this.genderNameField;
            }
            set
            {
                this.genderNameField = value;
            }
        }

        /// <remarks/>
        public string GenderNameLatin
        {
            get
            {
                return this.genderNameLatinField;
            }
            set
            {
                this.genderNameLatinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Nationality[] NationalityList
        {
            get
            {
                return this.nationalityListField;
            }
            set
            {
                this.nationalityListField = value;
            }
        }

        /// <remarks/>
        public PermanentAddress PermanentAddress
        {
            get
            {
                return this.permanentAddressField;
            }
            set
            {
                this.permanentAddressField = value;
            }
        }

        /// <remarks/>
        public double Height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeightSpecified
        {
            get
            {
                return this.heightFieldSpecified;
            }
            set
            {
                this.heightFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string EyesColor
        {
            get
            {
                return this.eyesColorField;
            }
            set
            {
                this.eyesColorField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        //public byte[] Picture
        //{
        //    get
        //    {
        //        return this.pictureField;
        //    }
        //    set
        //    {
        //        this.pictureField = value;
        //    }
        //}

        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        //public byte[] IdentitySignature
        //{
        //    get
        //    {
        //        return this.identitySignatureField;
        //    }
        //    set
        //    {
        //        this.identitySignatureField = value;
        //    }
        //}
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse")]
    public partial class ReturnInformation
    {

        private string returnCodeField;

        private string infoField;

        /// <remarks/>
        public string ReturnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }

        /// <remarks/>
        public string Info
        {
            get
            {
                return this.infoField;
            }
            set
            {
                this.infoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse")]
    public partial class PermanentAddress
    {

        private string districtNameField;

        private string districtNameLatinField;

        private string municipalityNameField;

        private string municipalityNameLatinField;

        private string settlementCodeField;

        private string settlementNameField;

        private string settlementNameLatinField;

        private string locationCodeField;

        private string locationNameField;

        private string locationNameLatinField;

        private string buildingNumberField;

        private string entranceField;

        private string floorField;

        private string apartmentField;

        /// <remarks/>
        public string DistrictName
        {
            get
            {
                return this.districtNameField;
            }
            set
            {
                this.districtNameField = value;
            }
        }

        /// <remarks/>
        public string DistrictNameLatin
        {
            get
            {
                return this.districtNameLatinField;
            }
            set
            {
                this.districtNameLatinField = value;
            }
        }

        /// <remarks/>
        public string MunicipalityName
        {
            get
            {
                return this.municipalityNameField;
            }
            set
            {
                this.municipalityNameField = value;
            }
        }

        /// <remarks/>
        public string MunicipalityNameLatin
        {
            get
            {
                return this.municipalityNameLatinField;
            }
            set
            {
                this.municipalityNameLatinField = value;
            }
        }

        /// <remarks/>
        public string SettlementCode
        {
            get
            {
                return this.settlementCodeField;
            }
            set
            {
                this.settlementCodeField = value;
            }
        }

        /// <remarks/>
        public string SettlementName
        {
            get
            {
                return this.settlementNameField;
            }
            set
            {
                this.settlementNameField = value;
            }
        }

        /// <remarks/>
        public string SettlementNameLatin
        {
            get
            {
                return this.settlementNameLatinField;
            }
            set
            {
                this.settlementNameLatinField = value;
            }
        }

        /// <remarks/>
        public string LocationCode
        {
            get
            {
                return this.locationCodeField;
            }
            set
            {
                this.locationCodeField = value;
            }
        }

        /// <remarks/>
        public string LocationName
        {
            get
            {
                return this.locationNameField;
            }
            set
            {
                this.locationNameField = value;
            }
        }

        /// <remarks/>
        public string LocationNameLatin
        {
            get
            {
                return this.locationNameLatinField;
            }
            set
            {
                this.locationNameLatinField = value;
            }
        }

        /// <remarks/>
        public string BuildingNumber
        {
            get
            {
                return this.buildingNumberField;
            }
            set
            {
                this.buildingNumberField = value;
            }
        }

        /// <remarks/>
        public string Entrance
        {
            get
            {
                return this.entranceField;
            }
            set
            {
                this.entranceField = value;
            }
        }

        /// <remarks/>
        public string Floor
        {
            get
            {
                return this.floorField;
            }
            set
            {
                this.floorField = value;
            }
        }

        /// <remarks/>
        public string Apartment
        {
            get
            {
                return this.apartmentField;
            }
            set
            {
                this.apartmentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse")]
    public partial class BirthPlace
    {

        private string countryCodeField;

        private string countryNameField;

        private string countryNameLatinField;

        private string territorialUnitNameField;

        private string districtNameField;

        private string municipalityNameField;

        /// <remarks/>
        public string CountryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }

        /// <remarks/>
        public string CountryName
        {
            get
            {
                return this.countryNameField;
            }
            set
            {
                this.countryNameField = value;
            }
        }

        /// <remarks/>
        public string CountryNameLatin
        {
            get
            {
                return this.countryNameLatinField;
            }
            set
            {
                this.countryNameLatinField = value;
            }
        }

        /// <remarks/>
        public string TerritorialUnitName
        {
            get
            {
                return this.territorialUnitNameField;
            }
            set
            {
                this.territorialUnitNameField = value;
            }
        }

        /// <remarks/>
        public string DistrictName
        {
            get
            {
                return this.districtNameField;
            }
            set
            {
                this.districtNameField = value;
            }
        }

        /// <remarks/>
        public string MunicipalityName
        {
            get
            {
                return this.municipalityNameField;
            }
            set
            {
                this.municipalityNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse")]
    public partial class GenderType
    {

        private string genderCodeField;

        private string cyrillicField;

        private string latinField;

        /// <remarks/>
        public string GenderCode
        {
            get
            {
                return this.genderCodeField;
            }
            set
            {
                this.genderCodeField = value;
            }
        }

        /// <remarks/>
        public string Cyrillic
        {
            get
            {
                return this.cyrillicField;
            }
            set
            {
                this.cyrillicField = value;
            }
        }

        /// <remarks/>
        public string Latin
        {
            get
            {
                return this.latinField;
            }
            set
            {
                this.latinField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse")]
    public partial class Nationality
    {

        private string nationalityCodeField;

        private string nationalityNameField;

        private string nationalityNameLatinField;

        /// <remarks/>
        public string NationalityCode
        {
            get
            {
                return this.nationalityCodeField;
            }
            set
            {
                this.nationalityCodeField = value;
            }
        }

        /// <remarks/>
        public string NationalityName
        {
            get
            {
                return this.nationalityNameField;
            }
            set
            {
                this.nationalityNameField = value;
            }
        }

        /// <remarks/>
        public string NationalityNameLatin
        {
            get
            {
                return this.nationalityNameLatinField;
            }
            set
            {
                this.nationalityNameLatinField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse")]
    public partial class ForeignCitizenType
    {

        private string pINField;

        private string pnField;

        private PersonNames namesField;

        private Nationality[] nationalityListField;

        private GenderType genderField;

        private System.DateTime birthDateField;

        private bool birthDateFieldSpecified;

        /// <remarks/>
        public string PIN
        {
            get
            {
                return this.pINField;
            }
            set
            {
                this.pINField = value;
            }
        }

        /// <remarks/>
        public string PN
        {
            get
            {
                return this.pnField;
            }
            set
            {
                this.pnField = value;
            }
        }

        /// <remarks/>
        public PersonNames Names
        {
            get
            {
                return this.namesField;
            }
            set
            {
                this.namesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Nationality[] NationalityList
        {
            get
            {
                return this.nationalityListField;
            }
            set
            {
                this.nationalityListField = value;
            }
        }

        /// <remarks/>
        public GenderType Gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime BirthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BirthDateSpecified
        {
            get
            {
                return this.birthDateFieldSpecified;
            }
            set
            {
                this.birthDateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse")]
    public partial class PersonNames
    {

        private string firstNameField;

        private string surnameField;

        private string familyNameField;

        private string firstNameLatinField;

        private string surnameLatinField;

        private string lastNameLatinField;

        /// <remarks/>
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        public string Surname
        {
            get
            {
                return this.surnameField;
            }
            set
            {
                this.surnameField = value;
            }
        }

        /// <remarks/>
        public string FamilyName
        {
            get
            {
                return this.familyNameField;
            }
            set
            {
                this.familyNameField = value;
            }
        }

        /// <remarks/>
        public string FirstNameLatin
        {
            get
            {
                return this.firstNameLatinField;
            }
            set
            {
                this.firstNameLatinField = value;
            }
        }

        /// <remarks/>
        public string SurnameLatin
        {
            get
            {
                return this.surnameLatinField;
            }
            set
            {
                this.surnameLatinField = value;
            }
        }

        /// <remarks/>
        public string LastNameLatin
        {
            get
            {
                return this.lastNameLatinField;
            }
            set
            {
                this.lastNameLatinField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse")]
    public partial class DLCategory
    {

        private string categoryField;

        private System.DateTime dateCategoryField;

        private System.DateTime endDateCategoryField;

        private bool endDateCategoryFieldSpecified;

        private string[] restrictionsField;

        /// <remarks/>
        public string Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DateCategory
        {
            get
            {
                return this.dateCategoryField;
            }
            set
            {
                this.dateCategoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime EndDateCategory
        {
            get
            {
                return this.endDateCategoryField;
            }
            set
            {
                this.endDateCategoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndDateCategorySpecified
        {
            get
            {
                return this.endDateCategoryFieldSpecified;
            }
            set
            {
                this.endDateCategoryFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Restrictions")]
        public string[] Restrictions
        {
            get
            {
                return this.restrictionsField;
            }
            set
            {
                this.restrictionsField = value;
            }
        }
    }
}
