//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
// Регистър на пенсионерите\Справка за доход от пенсия и добавка (УП-8)
namespace IOWebApplication.Infrastructure.Models.Regix.GetPensionIncomeAmountReport
{
    using System.ComponentModel.DataAnnotations;
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/NOI/RP/UP8Request")]
    [System.Xml.Serialization.XmlRootAttribute("UP8Request", Namespace = "http://egov.bg/RegiX/NOI/RP/UP8Request", IsNullable = false)]
    public partial class UP8RequestType
    {

        private string identifierField;

        private IdentifierType identifierTypeField;

        private PeriodType periodField;

        /// <remarks/>
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        /// <remarks/>
        public IdentifierType IdentifierType
        {
            get
            {
                return this.identifierTypeField;
            }
            set
            {
                this.identifierTypeField = value;
            }
        }

        /// <remarks/>
        public PeriodType Period
        {
            get
            {
                return this.periodField;
            }
            set
            {
                this.periodField = value;
            }
        }
    }

    /// <remarks/> 
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/NOI/RP")]
    [System.Xml.Serialization.XmlRootAttribute("EnumHack", Namespace = "http://egov.bg/RegiX/NOI/RP", IsNullable = false)]
    public enum IdentifierType
    {

        /// <remarks/>
        ЕГН,

        /// <remarks/>
        ЛНЧ,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/NOI/RP")]
    public partial class PeriodType
    {

        private MonthType fromField;

        private MonthType toField;

        /// <remarks/>
        public MonthType From
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }

        /// <remarks/>
        public MonthType To
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/NOI/RP")]
    public partial class MonthType
    {

        private string monthField;

        private string yearField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "gMonth")]
        public string Month
        {
            get
            {
                return this.monthField;
            }
            set
            {
                this.monthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "gYear")]
        public string Year
        {
            get
            {
                return this.yearField;
            }
            set
            {
                this.yearField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/NOI/RP/UP8Response")]
    [System.Xml.Serialization.XmlRootAttribute("UP8Response", Namespace = "http://egov.bg/RegiX/NOI/RP/UP8Response", IsNullable = false)]
    public partial class UP8ResponseType
    {

        private string titleField;

        private System.DateTime forDateField;

        private bool forDateFieldSpecified;

        private string territorialDivisionNOIField;

        private string identifierField;

        private PersonNames namesField;

        private string pensionerStatusField;

        private System.DateTime dateOfDeathField;

        private bool dateOfDeathFieldSpecified;

        private string contentTextField;

        private PensionPaymentType[] pensionPaymentsField;

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime ForDate
        {
            get
            {
                return this.forDateField;
            }
            set
            {
                this.forDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ForDateSpecified
        {
            get
            {
                return this.forDateFieldSpecified;
            }
            set
            {
                this.forDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string TerritorialDivisionNOI
        {
            get
            {
                return this.territorialDivisionNOIField;
            }
            set
            {
                this.territorialDivisionNOIField = value;
            }
        }

        /// <remarks/>
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        /// <remarks/>
        public PersonNames Names
        {
            get
            {
                return this.namesField;
            }
            set
            {
                this.namesField = value;
            }
        }

        /// <remarks/>
        public string PensionerStatus
        {
            get
            {
                return this.pensionerStatusField;
            }
            set
            {
                this.pensionerStatusField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DateOfDeath
        {
            get
            {
                return this.dateOfDeathField;
            }
            set
            {
                this.dateOfDeathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateOfDeathSpecified
        {
            get
            {
                return this.dateOfDeathFieldSpecified;
            }
            set
            {
                this.dateOfDeathFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string ContentText
        {
            get
            {
                return this.contentTextField;
            }
            set
            {
                this.contentTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PensionPayment", Namespace = "http://egov.bg/RegiX/NOI/RP", IsNullable = false)]
        public PensionPaymentType[] PensionPayments
        {
            get
            {
                return this.pensionPaymentsField;
            }
            set
            {
                this.pensionPaymentsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/NOI/RP")]
    public partial class PersonNames
    {

        private string nameField;

        private string surnameField;

        private string familyNameField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Surname
        {
            get
            {
                return this.surnameField;
            }
            set
            {
                this.surnameField = value;
            }
        }

        /// <remarks/>
        public string FamilyName
        {
            get
            {
                return this.familyNameField;
            }
            set
            {
                this.familyNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/NOI/RP")]
    public partial class PensionPaymentType
    {

        private string monthField;

        private decimal totalAmountField;

        private bool totalAmountFieldSpecified;

        private decimal pensionAmountField;

        private bool pensionAmountFieldSpecified;

        private decimal additionForAssistanceField;

        private bool additionForAssistanceFieldSpecified;

        private decimal otherAdditionField;

        private bool otherAdditionFieldSpecified;

        /// <remarks/>
        public string Month
        {
            get
            {
                return this.monthField;
            }
            set
            {
                this.monthField = value;
            }
        }

        /// <remarks/>
        public decimal TotalAmount
        {
            get
            {
                return this.totalAmountField;
            }
            set
            {
                this.totalAmountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalAmountSpecified
        {
            get
            {
                return this.totalAmountFieldSpecified;
            }
            set
            {
                this.totalAmountFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal PensionAmount
        {
            get
            {
                return this.pensionAmountField;
            }
            set
            {
                this.pensionAmountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PensionAmountSpecified
        {
            get
            {
                return this.pensionAmountFieldSpecified;
            }
            set
            {
                this.pensionAmountFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal AdditionForAssistance
        {
            get
            {
                return this.additionForAssistanceField;
            }
            set
            {
                this.additionForAssistanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdditionForAssistanceSpecified
        {
            get
            {
                return this.additionForAssistanceFieldSpecified;
            }
            set
            {
                this.additionForAssistanceFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal OtherAddition
        {
            get
            {
                return this.otherAdditionField;
            }
            set
            {
                this.otherAdditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OtherAdditionSpecified
        {
            get
            {
                return this.otherAdditionFieldSpecified;
            }
            set
            {
                this.otherAdditionFieldSpecified = value;
            }
        }
    }
}
