//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
//Регистър БУЛСТАТ\Справка по код на БУЛСТАТ или по фирмено дело за актуално състояние на субект на БУЛСТАТ
namespace IOWebApplication.Infrastructure.Models.Regix.GetStateOfPlay
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/GetStateOfPlayRequest")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.bulstat.bg/GetStateOfPlayRequest", IsNullable = false)]
    public partial class GetStateOfPlayRequest
    {

        private string uICField;

        private GetStateOfPlayRequestCase caseField;

        /// <remarks/>
        public string UIC
        {
            get
            {
                return this.uICField;
            }
            set
            {
                this.uICField = value;
            }
        }

        /// <remarks/>
        public GetStateOfPlayRequestCase Case
        {
            get
            {
                return this.caseField;
            }
            set
            {
                this.caseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.bulstat.bg/GetStateOfPlayRequest")]
    public partial class GetStateOfPlayRequestCase
    {

        private NomenclatureEntry courtField;

        private int yearField;

        private string numberField;

        /// <remarks/>
        public NomenclatureEntry Court
        {
            get
            {
                return this.courtField;
            }
            set
            {
                this.courtField = value;
            }
        }

        /// <remarks/>
        public int Year
        {
            get
            {
                return this.yearField;
            }
            set
            {
                this.yearField = value;
            }
        }

        /// <remarks/>
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/NomenclatureEntry")]
    public partial class NomenclatureEntry
    {

        private string codeField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/StateOfPlay")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.bulstat.bg/StateOfPlay", IsNullable = false)]
    public partial class StateOfPlay
    {

        private Subject subjectField;

        private Event eventField;

        private SubjectPropRepresentationType representationTypeField;

        private SubjectPropScopeOfActivity scopeOfActivityField;

        private SubjectPropActivityKID2008 mainActivity2008Field;

        private SubjectPropActivityKID2003 mainActivity2003Field;

        private SubjectPropInstallments[] installmentsField;

        private SubjectPropLifeTime lifeTimeField;

        private SubjectPropAccountingRecordForm accountingRecordFormField;

        private SubjectPropOwnershipForm[] ownershipFormsField;

        private SubjectPropFundingSource[] fundingSourcesField;

        private SubjectPropState stateField;

        private SubjectRelManager[] managersField;

        private SubjectRelPartner[] partnersField;

        private SubjectRelAssignee assigneeField;

        private SubjectRelBelonging belongingField;

        private SubjectPropCollectiveBody[] collectiveBodiesField;

        private SubjectPropActivityDate activityDateField;

        private SubjectPropActivityKID2008[] additionalActivities2008Field;

        private SubjectPropProfession[] professionsField;

        /// <remarks/>
        public Subject Subject
        {
            get
            {
                return this.subjectField;
            }
            set
            {
                this.subjectField = value;
            }
        }

        /// <remarks/>
        public Event Event
        {
            get
            {
                return this.eventField;
            }
            set
            {
                this.eventField = value;
            }
        }

        /// <remarks/>
        public SubjectPropRepresentationType RepresentationType
        {
            get
            {
                return this.representationTypeField;
            }
            set
            {
                this.representationTypeField = value;
            }
        }

        /// <remarks/>
        public SubjectPropScopeOfActivity ScopeOfActivity
        {
            get
            {
                return this.scopeOfActivityField;
            }
            set
            {
                this.scopeOfActivityField = value;
            }
        }

        /// <remarks/>
        public SubjectPropActivityKID2008 MainActivity2008
        {
            get
            {
                return this.mainActivity2008Field;
            }
            set
            {
                this.mainActivity2008Field = value;
            }
        }

        /// <remarks/>
        public SubjectPropActivityKID2003 MainActivity2003
        {
            get
            {
                return this.mainActivity2003Field;
            }
            set
            {
                this.mainActivity2003Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Installments")]
        public SubjectPropInstallments[] Installments
        {
            get
            {
                return this.installmentsField;
            }
            set
            {
                this.installmentsField = value;
            }
        }

        /// <remarks/>
        public SubjectPropLifeTime LifeTime
        {
            get
            {
                return this.lifeTimeField;
            }
            set
            {
                this.lifeTimeField = value;
            }
        }

        /// <remarks/>
        public SubjectPropAccountingRecordForm AccountingRecordForm
        {
            get
            {
                return this.accountingRecordFormField;
            }
            set
            {
                this.accountingRecordFormField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OwnershipForms")]
        public SubjectPropOwnershipForm[] OwnershipForms
        {
            get
            {
                return this.ownershipFormsField;
            }
            set
            {
                this.ownershipFormsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FundingSources")]
        public SubjectPropFundingSource[] FundingSources
        {
            get
            {
                return this.fundingSourcesField;
            }
            set
            {
                this.fundingSourcesField = value;
            }
        }

        /// <remarks/>
        public SubjectPropState State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Managers")]
        public SubjectRelManager[] Managers
        {
            get
            {
                return this.managersField;
            }
            set
            {
                this.managersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Partners")]
        public SubjectRelPartner[] Partners
        {
            get
            {
                return this.partnersField;
            }
            set
            {
                this.partnersField = value;
            }
        }

        /// <remarks/>
        public SubjectRelAssignee Assignee
        {
            get
            {
                return this.assigneeField;
            }
            set
            {
                this.assigneeField = value;
            }
        }

        /// <remarks/>
        public SubjectRelBelonging Belonging
        {
            get
            {
                return this.belongingField;
            }
            set
            {
                this.belongingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CollectiveBodies")]
        public SubjectPropCollectiveBody[] CollectiveBodies
        {
            get
            {
                return this.collectiveBodiesField;
            }
            set
            {
                this.collectiveBodiesField = value;
            }
        }

        /// <remarks/>
        public SubjectPropActivityDate ActivityDate
        {
            get
            {
                return this.activityDateField;
            }
            set
            {
                this.activityDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalActivities2008")]
        public SubjectPropActivityKID2008[] AdditionalActivities2008
        {
            get
            {
                return this.additionalActivities2008Field;
            }
            set
            {
                this.additionalActivities2008Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Professions")]
        public SubjectPropProfession[] Professions
        {
            get
            {
                return this.professionsField;
            }
            set
            {
                this.professionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/Subject")]
    public partial class Subject : Entry
    {

        private UIC uICField;

        private NomenclatureEntry subjectTypeField;

        private LegalEntity legalEntitySubjectField;

        private NaturalPerson naturalPersonSubjectField;

        private NomenclatureEntry countrySubjectField;

        private Communication[] communicationsField;

        private Address[] addressesField;

        private string remarkField;

        /// <remarks/>
        public UIC UIC
        {
            get
            {
                return this.uICField;
            }
            set
            {
                this.uICField = value;
            }
        }

        /// <remarks/>
        public NomenclatureEntry SubjectType
        {
            get
            {
                return this.subjectTypeField;
            }
            set
            {
                this.subjectTypeField = value;
            }
        }

        /// <remarks/>
        public LegalEntity LegalEntitySubject
        {
            get
            {
                return this.legalEntitySubjectField;
            }
            set
            {
                this.legalEntitySubjectField = value;
            }
        }

        /// <remarks/>
        public NaturalPerson NaturalPersonSubject
        {
            get
            {
                return this.naturalPersonSubjectField;
            }
            set
            {
                this.naturalPersonSubjectField = value;
            }
        }

        /// <remarks/>
        public NomenclatureEntry CountrySubject
        {
            get
            {
                return this.countrySubjectField;
            }
            set
            {
                this.countrySubjectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Communications")]
        public Communication[] Communications
        {
            get
            {
                return this.communicationsField;
            }
            set
            {
                this.communicationsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Addresses")]
        public Address[] Addresses
        {
            get
            {
                return this.addressesField;
            }
            set
            {
                this.addressesField = value;
            }
        }

        /// <remarks/>
        public string Remark
        {
            get
            {
                return this.remarkField;
            }
            set
            {
                this.remarkField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/UIC")]
    public partial class UIC : Entry
    {

        private string uIC1Field;

        private NomenclatureEntry uICTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UIC")]
        public string UIC1
        {
            get
            {
                return this.uIC1Field;
            }
            set
            {
                this.uIC1Field = value;
            }
        }

        /// <remarks/>
        public NomenclatureEntry UICType
        {
            get
            {
                return this.uICTypeField;
            }
            set
            {
                this.uICTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectPropState))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectPropScopeOfActivity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectPropRepresentationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectPropProfession))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectPropOwnershipForm))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectPropLifeTime))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectPropInstallments))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectPropFundingSource))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubscriptionElement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectRelPartner))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectRelManager))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectRelCollectiveBodyMember))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectRelBelonging))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectRelAssignee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectPropCollectiveBody))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectPropActivityKID2008))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectPropActivityKID2003))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectPropActivityDate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectPropAccountingRecordForm))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Event))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificationDoc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NaturalPerson))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LegalEntity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UIC))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Subject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Document))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Communication))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Case))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Address))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/Entry")]
    public partial class Entry
    {

        private System.DateTime entryTimeField;

        private bool entryTimeFieldSpecified;

        /// <remarks/>
        public System.DateTime EntryTime
        {
            get
            {
                return this.entryTimeField;
            }
            set
            {
                this.entryTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EntryTimeSpecified
        {
            get
            {
                return this.entryTimeFieldSpecified;
            }
            set
            {
                this.entryTimeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/SubjectPropState")]
    public partial class SubjectPropState : Entry
    {

        private NomenclatureEntry stateField;

        /// <remarks/>
        public NomenclatureEntry State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/SubjectPropScopeOfActivity")]
    public partial class SubjectPropScopeOfActivity : Entry
    {

        private string descriptionField;

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/SubjectPropRepresentationType")]
    public partial class SubjectPropRepresentationType : Entry
    {

        private NomenclatureEntry typeField;

        private string descriptionField;

        /// <remarks/>
        public NomenclatureEntry Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/SubjectPropProfession")]
    public partial class SubjectPropProfession : Entry
    {

        private NomenclatureEntry professionField;

        /// <remarks/>
        public NomenclatureEntry Profession
        {
            get
            {
                return this.professionField;
            }
            set
            {
                this.professionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/SubjectPropOwnershipForm")]
    public partial class SubjectPropOwnershipForm : Entry
    {

        private NomenclatureEntry formField;

        private decimal percentField;

        private bool percentFieldSpecified;

        /// <remarks/>
        public NomenclatureEntry Form
        {
            get
            {
                return this.formField;
            }
            set
            {
                this.formField = value;
            }
        }

        /// <remarks/>
        public decimal Percent
        {
            get
            {
                return this.percentField;
            }
            set
            {
                this.percentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PercentSpecified
        {
            get
            {
                return this.percentFieldSpecified;
            }
            set
            {
                this.percentFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/SubjectPropLifeTime")]
    public partial class SubjectPropLifeTime : Entry
    {

        private string dateField;

        private string descriptionField;

        /// <remarks/>
        public string Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/SubjectPropInstallments")]
    public partial class SubjectPropInstallments : Entry
    {

        private int countField;

        private bool countFieldSpecified;

        private decimal amountField;

        private bool amountFieldSpecified;

        /// <remarks/>
        public int Count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified
        {
            get
            {
                return this.countFieldSpecified;
            }
            set
            {
                this.countFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified
        {
            get
            {
                return this.amountFieldSpecified;
            }
            set
            {
                this.amountFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/SubjectPropFundingSource")]
    public partial class SubjectPropFundingSource : Entry
    {

        private NomenclatureEntry sourceField;

        private decimal percentField;

        private bool percentFieldSpecified;

        /// <remarks/>
        public NomenclatureEntry Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        public decimal Percent
        {
            get
            {
                return this.percentField;
            }
            set
            {
                this.percentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PercentSpecified
        {
            get
            {
                return this.percentFieldSpecified;
            }
            set
            {
                this.percentFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectRelPartner))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectRelManager))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectRelCollectiveBodyMember))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectRelBelonging))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectRelAssignee))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/SubscriptionElement")]
    public partial class SubscriptionElement : Entry
    {

        private SubscriptionElementOperationType operationTypeField;

        private bool operationTypeFieldSpecified;

        /// <remarks/>
        public SubscriptionElementOperationType OperationType
        {
            get
            {
                return this.operationTypeField;
            }
            set
            {
                this.operationTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperationTypeSpecified
        {
            get
            {
                return this.operationTypeFieldSpecified;
            }
            set
            {
                this.operationTypeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.bulstat.bg/SubscriptionElement")]
    public enum SubscriptionElementOperationType
    {

        /// <remarks/>
        register,

        /// <remarks/>
        erase,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/SubjectRelPartner")]
    public partial class SubjectRelPartner : SubscriptionElement
    {

        private Subject relatedSubjectField;

        private NomenclatureEntry roleField;

        private decimal percentField;

        private bool percentFieldSpecified;

        private decimal amountField;

        private bool amountFieldSpecified;

        /// <remarks/>
        public Subject RelatedSubject
        {
            get
            {
                return this.relatedSubjectField;
            }
            set
            {
                this.relatedSubjectField = value;
            }
        }

        /// <remarks/>
        public NomenclatureEntry Role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }

        /// <remarks/>
        public decimal Percent
        {
            get
            {
                return this.percentField;
            }
            set
            {
                this.percentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PercentSpecified
        {
            get
            {
                return this.percentFieldSpecified;
            }
            set
            {
                this.percentFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified
        {
            get
            {
                return this.amountFieldSpecified;
            }
            set
            {
                this.amountFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/SubjectRelManager")]
    public partial class SubjectRelManager : SubscriptionElement
    {

        private Subject relatedSubjectField;

        private NomenclatureEntry positionField;

        private Subject[] representedSubjectsField;

        /// <remarks/>
        public Subject RelatedSubject
        {
            get
            {
                return this.relatedSubjectField;
            }
            set
            {
                this.relatedSubjectField = value;
            }
        }

        /// <remarks/>
        public NomenclatureEntry Position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RepresentedSubjects")]
        public Subject[] RepresentedSubjects
        {
            get
            {
                return this.representedSubjectsField;
            }
            set
            {
                this.representedSubjectsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/SubjectRelCollectiveBodyMember")]
    public partial class SubjectRelCollectiveBodyMember : SubscriptionElement
    {

        private Subject relatedSubjectField;

        private NomenclatureEntry positionField;

        private Subject[] representedSubjectsField;

        /// <remarks/>
        public Subject RelatedSubject
        {
            get
            {
                return this.relatedSubjectField;
            }
            set
            {
                this.relatedSubjectField = value;
            }
        }

        /// <remarks/>
        public NomenclatureEntry Position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RepresentedSubjects")]
        public Subject[] RepresentedSubjects
        {
            get
            {
                return this.representedSubjectsField;
            }
            set
            {
                this.representedSubjectsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/SubjectRelBelonging")]
    public partial class SubjectRelBelonging : SubscriptionElement
    {

        private Subject relatedSubjectField;

        private NomenclatureEntry typeField;

        /// <remarks/>
        public Subject RelatedSubject
        {
            get
            {
                return this.relatedSubjectField;
            }
            set
            {
                this.relatedSubjectField = value;
            }
        }

        /// <remarks/>
        public NomenclatureEntry Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/SubjectRelAssignee")]
    public partial class SubjectRelAssignee : SubscriptionElement
    {

        private Subject[] relatedSubjectsField;

        private NomenclatureEntry typeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RelatedSubjects")]
        public Subject[] RelatedSubjects
        {
            get
            {
                return this.relatedSubjectsField;
            }
            set
            {
                this.relatedSubjectsField = value;
            }
        }

        /// <remarks/>
        public NomenclatureEntry Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/SubjectPropCollectiveBody")]
    public partial class SubjectPropCollectiveBody : Entry
    {

        private NomenclatureEntry typeField;

        private SubjectRelCollectiveBodyMember[] membersField;

        /// <remarks/>
        public NomenclatureEntry Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Members")]
        public SubjectRelCollectiveBodyMember[] Members
        {
            get
            {
                return this.membersField;
            }
            set
            {
                this.membersField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/SubjectPropActivityKID2008")]
    public partial class SubjectPropActivityKID2008 : Entry
    {

        private NomenclatureEntry kID2008Field;

        /// <remarks/>
        public NomenclatureEntry KID2008
        {
            get
            {
                return this.kID2008Field;
            }
            set
            {
                this.kID2008Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/SubjectPropActivityKID2003")]
    public partial class SubjectPropActivityKID2003 : Entry
    {

        private NomenclatureEntry nKID2003Field;

        /// <remarks/>
        public NomenclatureEntry NKID2003
        {
            get
            {
                return this.nKID2003Field;
            }
            set
            {
                this.nKID2003Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/SubjectPropActivityDate")]
    public partial class SubjectPropActivityDate : Entry
    {

        private NomenclatureEntry typeField;

        private string dateField;

        /// <remarks/>
        public NomenclatureEntry Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/SubjectPropAccountingRecordForm")]
    public partial class SubjectPropAccountingRecordForm : Entry
    {

        private NomenclatureEntry formField;

        /// <remarks/>
        public NomenclatureEntry Form
        {
            get
            {
                return this.formField;
            }
            set
            {
                this.formField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/Event")]
    public partial class Event : Entry
    {

        private Document documentField;

        private NomenclatureEntry eventTypeField;

        private string eventDateField;

        private NomenclatureEntry legalBaseField;

        private NomenclatureEntry entryTypeField;

        private Case caseField;

        /// <remarks/>
        public Document Document
        {
            get
            {
                return this.documentField;
            }
            set
            {
                this.documentField = value;
            }
        }

        /// <remarks/>
        public NomenclatureEntry EventType
        {
            get
            {
                return this.eventTypeField;
            }
            set
            {
                this.eventTypeField = value;
            }
        }

        /// <remarks/>
        public string EventDate
        {
            get
            {
                return this.eventDateField;
            }
            set
            {
                this.eventDateField = value;
            }
        }

        /// <remarks/>
        public NomenclatureEntry LegalBase
        {
            get
            {
                return this.legalBaseField;
            }
            set
            {
                this.legalBaseField = value;
            }
        }

        /// <remarks/>
        public NomenclatureEntry EntryType
        {
            get
            {
                return this.entryTypeField;
            }
            set
            {
                this.entryTypeField = value;
            }
        }

        /// <remarks/>
        public Case Case
        {
            get
            {
                return this.caseField;
            }
            set
            {
                this.caseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/Document")]
    public partial class Document : Entry
    {

        private NomenclatureEntry documentTypeField;

        private string documentNumberField;

        private string documentDateField;

        private string validFromDateField;

        private string documentNameField;

        private Subject authorField;

        private string authorNameField;

        /// <remarks/>
        public NomenclatureEntry DocumentType
        {
            get
            {
                return this.documentTypeField;
            }
            set
            {
                this.documentTypeField = value;
            }
        }

        /// <remarks/>
        public string DocumentNumber
        {
            get
            {
                return this.documentNumberField;
            }
            set
            {
                this.documentNumberField = value;
            }
        }

        /// <remarks/>
        public string DocumentDate
        {
            get
            {
                return this.documentDateField;
            }
            set
            {
                this.documentDateField = value;
            }
        }

        /// <remarks/>
        public string ValidFromDate
        {
            get
            {
                return this.validFromDateField;
            }
            set
            {
                this.validFromDateField = value;
            }
        }

        /// <remarks/>
        public string DocumentName
        {
            get
            {
                return this.documentNameField;
            }
            set
            {
                this.documentNameField = value;
            }
        }

        /// <remarks/>
        public Subject Author
        {
            get
            {
                return this.authorField;
            }
            set
            {
                this.authorField = value;
            }
        }

        /// <remarks/>
        public string AuthorName
        {
            get
            {
                return this.authorNameField;
            }
            set
            {
                this.authorNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/Case")]
    public partial class Case : Entry
    {

        private NomenclatureEntry courtField;

        private int yearField;

        private bool yearFieldSpecified;

        private string numberField;

        private string batchField;

        private int registerField;

        private bool registerFieldSpecified;

        private string chapterField;

        private int pageNumberField;

        private bool pageNumberFieldSpecified;

        /// <remarks/>
        public NomenclatureEntry Court
        {
            get
            {
                return this.courtField;
            }
            set
            {
                this.courtField = value;
            }
        }

        /// <remarks/>
        public int Year
        {
            get
            {
                return this.yearField;
            }
            set
            {
                this.yearField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YearSpecified
        {
            get
            {
                return this.yearFieldSpecified;
            }
            set
            {
                this.yearFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        public string Batch
        {
            get
            {
                return this.batchField;
            }
            set
            {
                this.batchField = value;
            }
        }

        /// <remarks/>
        public int Register
        {
            get
            {
                return this.registerField;
            }
            set
            {
                this.registerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegisterSpecified
        {
            get
            {
                return this.registerFieldSpecified;
            }
            set
            {
                this.registerFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Chapter
        {
            get
            {
                return this.chapterField;
            }
            set
            {
                this.chapterField = value;
            }
        }

        /// <remarks/>
        public int PageNumber
        {
            get
            {
                return this.pageNumberField;
            }
            set
            {
                this.pageNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PageNumberSpecified
        {
            get
            {
                return this.pageNumberFieldSpecified;
            }
            set
            {
                this.pageNumberFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/IdentificationDoc")]
    public partial class IdentificationDoc : Entry
    {

        private NomenclatureEntry iDTypeField;

        private string iDNumberField;

        private NomenclatureEntry countryField;

        private string issueDateField;

        private string expiryDateField;

        /// <remarks/>
        public NomenclatureEntry IDType
        {
            get
            {
                return this.iDTypeField;
            }
            set
            {
                this.iDTypeField = value;
            }
        }

        /// <remarks/>
        public string IDNumber
        {
            get
            {
                return this.iDNumberField;
            }
            set
            {
                this.iDNumberField = value;
            }
        }

        /// <remarks/>
        public NomenclatureEntry Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        public string IssueDate
        {
            get
            {
                return this.issueDateField;
            }
            set
            {
                this.issueDateField = value;
            }
        }

        /// <remarks/>
        public string ExpiryDate
        {
            get
            {
                return this.expiryDateField;
            }
            set
            {
                this.expiryDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/NaturalPerson")]
    public partial class NaturalPerson : Entry
    {

        private NomenclatureEntry countryField;

        private string eGNField;

        private string lNCField;

        private string cyrillicNameField;

        private string latinNameField;

        private string birthDateField;

        private IdentificationDoc identificationDocField;

        /// <remarks/>
        public NomenclatureEntry Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        public string EGN
        {
            get
            {
                return this.eGNField;
            }
            set
            {
                this.eGNField = value;
            }
        }

        /// <remarks/>
        public string LNC
        {
            get
            {
                return this.lNCField;
            }
            set
            {
                this.lNCField = value;
            }
        }

        /// <remarks/>
        public string CyrillicName
        {
            get
            {
                return this.cyrillicNameField;
            }
            set
            {
                this.cyrillicNameField = value;
            }
        }

        /// <remarks/>
        public string LatinName
        {
            get
            {
                return this.latinNameField;
            }
            set
            {
                this.latinNameField = value;
            }
        }

        /// <remarks/>
        public string BirthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }

        /// <remarks/>
        public IdentificationDoc IdentificationDoc
        {
            get
            {
                return this.identificationDocField;
            }
            set
            {
                this.identificationDocField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/LegalEntity")]
    public partial class LegalEntity : Entry
    {

        private NomenclatureEntry countryField;

        private NomenclatureEntry legalFormField;

        private NomenclatureEntry legalStatuteField;

        private NomenclatureEntry subjectGroupField;

        private string cyrillicFullNameField;

        private string cyrillicShortNameField;

        private string latinFullNameField;

        private NomenclatureEntry subordinateLevelField;

        private string tRStatusField;

        /// <remarks/>
        public NomenclatureEntry Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        public NomenclatureEntry LegalForm
        {
            get
            {
                return this.legalFormField;
            }
            set
            {
                this.legalFormField = value;
            }
        }

        /// <remarks/>
        public NomenclatureEntry LegalStatute
        {
            get
            {
                return this.legalStatuteField;
            }
            set
            {
                this.legalStatuteField = value;
            }
        }

        /// <remarks/>
        public NomenclatureEntry SubjectGroup
        {
            get
            {
                return this.subjectGroupField;
            }
            set
            {
                this.subjectGroupField = value;
            }
        }

        /// <remarks/>
        public string CyrillicFullName
        {
            get
            {
                return this.cyrillicFullNameField;
            }
            set
            {
                this.cyrillicFullNameField = value;
            }
        }

        /// <remarks/>
        public string CyrillicShortName
        {
            get
            {
                return this.cyrillicShortNameField;
            }
            set
            {
                this.cyrillicShortNameField = value;
            }
        }

        /// <remarks/>
        public string LatinFullName
        {
            get
            {
                return this.latinFullNameField;
            }
            set
            {
                this.latinFullNameField = value;
            }
        }

        /// <remarks/>
        public NomenclatureEntry SubordinateLevel
        {
            get
            {
                return this.subordinateLevelField;
            }
            set
            {
                this.subordinateLevelField = value;
            }
        }

        /// <remarks/>
        public string TRStatus
        {
            get
            {
                return this.tRStatusField;
            }
            set
            {
                this.tRStatusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/Communication")]
    public partial class Communication : Entry
    {

        private NomenclatureEntry typeField;

        private string valueField;

        /// <remarks/>
        public NomenclatureEntry Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bulstat.bg/Address")]
    public partial class Address : Entry
    {

        private NomenclatureEntry addressTypeField;

        private NomenclatureEntry countryField;

        private string postalCodeField;

        private string postalBoxField;

        private string foreignLocationField;

        private NomenclatureEntry locationField;

        private NomenclatureEntry regionField;

        private string streetField;

        private string streetNumberField;

        private string buildingField;

        private string entranceField;

        private string floorField;

        private string apartmentField;

        /// <remarks/>
        public NomenclatureEntry AddressType
        {
            get
            {
                return this.addressTypeField;
            }
            set
            {
                this.addressTypeField = value;
            }
        }

        /// <remarks/>
        public NomenclatureEntry Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        /// <remarks/>
        public string PostalBox
        {
            get
            {
                return this.postalBoxField;
            }
            set
            {
                this.postalBoxField = value;
            }
        }

        /// <remarks/>
        public string ForeignLocation
        {
            get
            {
                return this.foreignLocationField;
            }
            set
            {
                this.foreignLocationField = value;
            }
        }

        /// <remarks/>
        public NomenclatureEntry Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        public NomenclatureEntry Region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }

        /// <remarks/>
        public string Street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }

        /// <remarks/>
        public string StreetNumber
        {
            get
            {
                return this.streetNumberField;
            }
            set
            {
                this.streetNumberField = value;
            }
        }

        /// <remarks/>
        public string Building
        {
            get
            {
                return this.buildingField;
            }
            set
            {
                this.buildingField = value;
            }
        }

        /// <remarks/>
        public string Entrance
        {
            get
            {
                return this.entranceField;
            }
            set
            {
                this.entranceField = value;
            }
        }

        /// <remarks/>
        public string Floor
        {
            get
            {
                return this.floorField;
            }
            set
            {
                this.floorField = value;
            }
        }

        /// <remarks/>
        public string Apartment
        {
            get
            {
                return this.apartmentField;
            }
            set
            {
                this.apartmentField = value;
            }
        }
    }
}

