// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace IOWebApplication.Infrastructure.Models.Regix.RelationsSearch
{
    using System.Xml.Serialization;

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GRAO/NBD/RelationsRequest")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://egov.bg/RegiX/GRAO/NBD/RelationsRequest", IsNullable = false)]
    public partial class RelationsRequestType
    {

        private string eGNField;

        /// <remarks/>
        public string EGN
        {
            get
            {
                return this.eGNField;
            }
            set
            {
                this.eGNField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GRAO/NBD/RelationsResponse")]
    [System.Xml.Serialization.XmlRootAttribute("RelationsResponse", Namespace = "http://egov.bg/RegiX/GRAO/NBD/RelationsResponse", IsNullable = false)]
    public partial class RelationsResponseType
    {

        private PersonRelationType[] personRelationsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PersonRelations")]
        public PersonRelationType[] PersonRelations
        {
            get
            {
                return this.personRelationsField;
            }
            set
            {
                this.personRelationsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GRAO/NBD")]
    public partial class PersonRelationType
    {

        private RelationType relationCodeField;

        private bool relationCodeFieldSpecified;

        private string eGNField;

        private System.DateTime birthDateField;

        private bool birthDateFieldSpecified;

        private string firstNameField;

        private string surNameField;

        private string familyNameField;

        private Gender genderField;

        private Nationality nationalityField;

        private System.DateTime deathDateField;

        private bool deathDateFieldSpecified;

        /// <remarks/>
        public RelationType RelationCode
        {
            get
            {
                return this.relationCodeField;
            }
            set
            {
                this.relationCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RelationCodeSpecified
        {
            get
            {
                return this.relationCodeFieldSpecified;
            }
            set
            {
                this.relationCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string EGN
        {
            get
            {
                return this.eGNField;
            }
            set
            {
                this.eGNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime BirthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BirthDateSpecified
        {
            get
            {
                return this.birthDateFieldSpecified;
            }
            set
            {
                this.birthDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        public string SurName
        {
            get
            {
                return this.surNameField;
            }
            set
            {
                this.surNameField = value;
            }
        }

        /// <remarks/>
        public string FamilyName
        {
            get
            {
                return this.familyNameField;
            }
            set
            {
                this.familyNameField = value;
            }
        }

        /// <remarks/>
        public Gender Gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }

        /// <remarks/>
        public Nationality Nationality
        {
            get
            {
                return this.nationalityField;
            }
            set
            {
                this.nationalityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DeathDate
        {
            get
            {
                return this.deathDateField;
            }
            set
            {
                this.deathDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeathDateSpecified
        {
            get
            {
                return this.deathDateFieldSpecified;
            }
            set
            {
                this.deathDateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GRAO/NBD")]
    public enum RelationType
    {

        /// <remarks/>
        Баща,

        /// <remarks/>
        Осиновител,

        /// <remarks/>
        Майка,

        /// <remarks/>
        Осиновителка,

        /// <remarks/>
        Син,

        /// <remarks/>
        Дъщеря,

        /// <remarks/>
        Брат,

        /// <remarks/>
        Сестра,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GRAO/NBD")]
    public partial class Gender
    {

        private int genderCodeField;

        private bool genderCodeFieldSpecified;

        private GenderNameType genderNameField;

        private bool genderNameFieldSpecified;

        /// <remarks/>
        public int GenderCode
        {
            get
            {
                return this.genderCodeField;
            }
            set
            {
                this.genderCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenderCodeSpecified
        {
            get
            {
                return this.genderCodeFieldSpecified;
            }
            set
            {
                this.genderCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public GenderNameType GenderName
        {
            get
            {
                return this.genderNameField;
            }
            set
            {
                this.genderNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenderNameSpecified
        {
            get
            {
                return this.genderNameFieldSpecified;
            }
            set
            {
                this.genderNameFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GRAO/NBD")]
    public enum GenderNameType
    {

        /// <remarks/>
        Мъж,

        /// <remarks/>
        Жена,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GRAO/NBD")]
    public partial class Nationality
    {

        private string nationalityCodeField;

        private string nationalityNameField;

        private string nationalityCode2Field;

        private string nationalityName2Field;

        /// <remarks/>
        public string NationalityCode
        {
            get
            {
                return this.nationalityCodeField;
            }
            set
            {
                this.nationalityCodeField = value;
            }
        }

        /// <remarks/>
        public string NationalityName
        {
            get
            {
                return this.nationalityNameField;
            }
            set
            {
                this.nationalityNameField = value;
            }
        }

        /// <remarks/>
        public string NationalityCode2
        {
            get
            {
                return this.nationalityCode2Field;
            }
            set
            {
                this.nationalityCode2Field = value;
            }
        }

        /// <remarks/>
        public string NationalityName2
        {
            get
            {
                return this.nationalityName2Field;
            }
            set
            {
                this.nationalityName2Field = value;
            }
        }
    }
}
