//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
//Регистър на обезщетенията за болест, майчинство и безработица\Справка за изплатено парично обезщетение при временна неработоспособност, трудоустрояване и майчинство и/или помощ по период на дата на ведомост /дата на плащане
namespace IOWebApplication.Infrastructure.Models.Regix.SearchDisabilityCompensationByPaymentPeriod
{
    using System.ComponentModel.DataAnnotations;
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/NOI/RO/POVNVEDRequest")]
    [System.Xml.Serialization.XmlRootAttribute("POVNVEDRequest", Namespace = "http://egov.bg/RegiX/NOI/RO/POVNVEDRequest", IsNullable = false)]
    public partial class POVNVEDRequestType
    {

        private string identifierField;

        private IdentifierType identifierTypeField;

        private System.DateTime dateFromField;

        private System.DateTime dateToField;

        /// <remarks/>
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        /// <remarks/>
        public IdentifierType IdentifierType
        {
            get
            {
                return this.identifierTypeField;
            }
            set
            {
                this.identifierTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DateFrom
        {
            get
            {
                return this.dateFromField;
            }
            set
            {
                this.dateFromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DateTo
        {
            get
            {
                return this.dateToField;
            }
            set
            {
                this.dateToField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/NOI/RO")]
    [System.Xml.Serialization.XmlRootAttribute("Test", Namespace = "http://egov.bg/RegiX/NOI/RO", IsNullable = false)]
    public enum IdentifierType
    {

        /// <remarks/>
        ЕГН,

        /// <remarks/>
        ЛНЧ,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/NOI/RO/POVNVEDResponse")]
    [System.Xml.Serialization.XmlRootAttribute("POVNVEDResponse", Namespace = "http://egov.bg/RegiX/NOI/RO/POVNVEDResponse", IsNullable = false)]
    public partial class POVNVEDResponseType
    {

        private string identifierField;

        private IdentifierType identifierTypeField;

        private bool identifierTypeFieldSpecified;

        private string namesField;

        private PaymentWithDateType[] paymentDataField;

        private string missingDataField;

        /// <remarks/>
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        /// <remarks/>
        public IdentifierType IdentifierType
        {
            get
            {
                return this.identifierTypeField;
            }
            set
            {
                this.identifierTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdentifierTypeSpecified
        {
            get
            {
                return this.identifierTypeFieldSpecified;
            }
            set
            {
                this.identifierTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Names
        {
            get
            {
                return this.namesField;
            }
            set
            {
                this.namesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Payment", Namespace = "http://egov.bg/RegiX/NOI/RO", IsNullable = false)]
        public PaymentWithDateType[] PaymentData
        {
            get
            {
                return this.paymentDataField;
            }
            set
            {
                this.paymentDataField = value;
            }
        }

        /// <remarks/>
        public string MissingData
        {
            get
            {
                return this.missingDataField;
            }
            set
            {
                this.missingDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/NOI/RO")]
    public partial class PaymentWithDateType
    {

        private string benefitTypeField;

        private string benefitMonthField;

        private string benefitYearField;

        private decimal benefitAmountField;

        private bool benefitAmountFieldSpecified;

        private System.DateTime benefitDatePaymentField;

        private bool benefitDatePaymentFieldSpecified;

        /// <remarks/>
        public string BenefitType
        {
            get
            {
                return this.benefitTypeField;
            }
            set
            {
                this.benefitTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "gMonth")]
        public string BenefitMonth
        {
            get
            {
                return this.benefitMonthField;
            }
            set
            {
                this.benefitMonthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "gYear")]
        public string BenefitYear
        {
            get
            {
                return this.benefitYearField;
            }
            set
            {
                this.benefitYearField = value;
            }
        }

        /// <remarks/>
        public decimal BenefitAmount
        {
            get
            {
                return this.benefitAmountField;
            }
            set
            {
                this.benefitAmountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BenefitAmountSpecified
        {
            get
            {
                return this.benefitAmountFieldSpecified;
            }
            set
            {
                this.benefitAmountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime BenefitDatePayment
        {
            get
            {
                return this.benefitDatePaymentField;
            }
            set
            {
                this.benefitDatePaymentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BenefitDatePaymentSpecified
        {
            get
            {
                return this.benefitDatePaymentFieldSpecified;
            }
            set
            {
                this.benefitDatePaymentFieldSpecified = value;
            }
        }
    }
}
