//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IOWebApplication.Infrastructure.Integrations
{
    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.6.81.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Transfer
    {

        private string programField;

        private double versionField;

        private CaseType caseField;

        /// <remarks/>
        public string program
        {
            get
            {
                return this.programField;
            }
            set
            {
                this.programField = value;
            }
        }

        /// <remarks/>
        public double version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public CaseType Case
        {
            get
            {
                return this.caseField;
            }
            set
            {
                this.caseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CaseType
    {

        private ExtensionsType extensionsField;

        private string case_idField;

        private int case_actionField;

        private int case_courtField;

        private int case_kindField;

        private int case_noField;

        private string case_yearField;

        private System.DateTime case_dateField;

        private SurroundType[] surroundField;

        private SessionType[] sessionField;

        private InDocType inDocField;

        private SideType[] sideField;

        private JudgeType judgeField;

        /// <remarks/>
        public ExtensionsType extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }

        /// <remarks/>
        public string case_id
        {
            get
            {
                return this.case_idField;
            }
            set
            {
                this.case_idField = value;
            }
        }

        /// <remarks/>
        public int case_action
        {
            get
            {
                return this.case_actionField;
            }
            set
            {
                this.case_actionField = value;
            }
        }

        /// <remarks/>
        public int case_court
        {
            get
            {
                return this.case_courtField;
            }
            set
            {
                this.case_courtField = value;
            }
        }

        /// <remarks/>
        public int case_kind
        {
            get
            {
                return this.case_kindField;
            }
            set
            {
                this.case_kindField = value;
            }
        }

        /// <remarks/>
        public int case_no
        {
            get
            {
                return this.case_noField;
            }
            set
            {
                this.case_noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "gYear")]
        public string case_year
        {
            get
            {
                return this.case_yearField;
            }
            set
            {
                this.case_yearField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime case_date
        {
            get
            {
                return this.case_dateField;
            }
            set
            {
                this.case_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Surround")]
        public SurroundType[] Surround
        {
            get
            {
                return this.surroundField;
            }
            set
            {
                this.surroundField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Session")]
        public SessionType[] Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }

        /// <remarks/>
        public InDocType InDoc
        {
            get
            {
                return this.inDocField;
            }
            set
            {
                this.inDocField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Side")]
        public SideType[] Side
        {
            get
            {
                return this.sideField;
            }
            set
            {
                this.sideField = value;
            }
        }

        /// <remarks/>
        public JudgeType Judge
        {
            get
            {
                return this.judgeField;
            }
            set
            {
                this.judgeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExtensionsType
    {

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InDocType
    {

        private ExtensionsType extensionsField;

        private string indoc_idField;

        private int indoc_kindField;

        private int indoc_noField;

        private bool indoc_noFieldSpecified;

        private int indoc_yearField;

        private System.DateTime indoc_dateField;

        /// <remarks/>
        public ExtensionsType extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }

        /// <remarks/>
        public string indoc_id
        {
            get
            {
                return this.indoc_idField;
            }
            set
            {
                this.indoc_idField = value;
            }
        }

        /// <remarks/>
        public int indoc_kind
        {
            get
            {
                return this.indoc_kindField;
            }
            set
            {
                this.indoc_kindField = value;
            }
        }

        /// <remarks/>
        public int indoc_no
        {
            get
            {
                return this.indoc_noField;
            }
            set
            {
                this.indoc_noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indoc_noSpecified
        {
            get
            {
                return this.indoc_noFieldSpecified;
            }
            set
            {
                this.indoc_noFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int indoc_year
        {
            get
            {
                return this.indoc_yearField;
            }
            set
            {
                this.indoc_yearField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime indoc_date
        {
            get
            {
                return this.indoc_dateField;
            }
            set
            {
                this.indoc_dateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReturnType
    {

        private ExtensionsType extensionsField;

        private string return_resultField;

        private string return_result2Field;

        /// <remarks/>
        public ExtensionsType extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }

        /// <remarks/>
        public string return_result
        {
            get
            {
                return this.return_resultField;
            }
            set
            {
                this.return_resultField = value;
            }
        }

        /// <remarks/>
        public string return_result2
        {
            get
            {
                return this.return_result2Field;
            }
            set
            {
                this.return_result2Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendToType
    {

        private ExtensionsType extensionsField;

        private string sendto_idField;

        private int sendto_actionField;

        private int sendto_kindField;

        private int sendto_noField;

        private string sendto_yearField;

        private System.DateTime sendto_dateField;

        private int sendto_courtField;

        private ReturnType returnField;

        /// <remarks/>
        public ExtensionsType extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }

        /// <remarks/>
        public string sendto_id
        {
            get
            {
                return this.sendto_idField;
            }
            set
            {
                this.sendto_idField = value;
            }
        }

        /// <remarks/>
        public int sendto_action
        {
            get
            {
                return this.sendto_actionField;
            }
            set
            {
                this.sendto_actionField = value;
            }
        }

        /// <remarks/>
        public int sendto_kind
        {
            get
            {
                return this.sendto_kindField;
            }
            set
            {
                this.sendto_kindField = value;
            }
        }

        /// <remarks/>
        public int sendto_no
        {
            get
            {
                return this.sendto_noField;
            }
            set
            {
                this.sendto_noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "gYear")]
        public string sendto_year
        {
            get
            {
                return this.sendto_yearField;
            }
            set
            {
                this.sendto_yearField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime sendto_date
        {
            get
            {
                return this.sendto_dateField;
            }
            set
            {
                this.sendto_dateField = value;
            }
        }

        /// <remarks/>
        public int sendto_court
        {
            get
            {
                return this.sendto_courtField;
            }
            set
            {
                this.sendto_courtField = value;
            }
        }

        /// <remarks/>
        public ReturnType @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AppealType
    {

        private ExtensionsType extensionsField;

        private string appeal_idField;

        private int appeal_actionField;

        private int appeal_kindField;

        private int appeal_noField;

        private string appeal_yearField;

        private System.DateTime appeal_dateField;

        private SideType[] sideField;

        private SendToType[] sendToField;

        /// <remarks/>
        public ExtensionsType extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }

        /// <remarks/>
        public string appeal_id
        {
            get
            {
                return this.appeal_idField;
            }
            set
            {
                this.appeal_idField = value;
            }
        }

        /// <remarks/>
        public int appeal_action
        {
            get
            {
                return this.appeal_actionField;
            }
            set
            {
                this.appeal_actionField = value;
            }
        }

        /// <remarks/>
        public int appeal_kind
        {
            get
            {
                return this.appeal_kindField;
            }
            set
            {
                this.appeal_kindField = value;
            }
        }

        /// <remarks/>
        public int appeal_no
        {
            get
            {
                return this.appeal_noField;
            }
            set
            {
                this.appeal_noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "gYear")]
        public string appeal_year
        {
            get
            {
                return this.appeal_yearField;
            }
            set
            {
                this.appeal_yearField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime appeal_date
        {
            get
            {
                return this.appeal_dateField;
            }
            set
            {
                this.appeal_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Side")]
        public SideType[] Side
        {
            get
            {
                return this.sideField;
            }
            set
            {
                this.sideField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SendTo")]
        public SendToType[] SendTo
        {
            get
            {
                return this.sendToField;
            }
            set
            {
                this.sendToField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SideType
    {

        private ExtensionsType extensionsField;

        private string side_idField;

        private int side_involvementField;

        private object itemField;

        /// <remarks/>
        public ExtensionsType extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }

        /// <remarks/>
        public string side_id
        {
            get
            {
                return this.side_idField;
            }
            set
            {
                this.side_idField = value;
            }
        }

        /// <remarks/>
        public int side_involvement
        {
            get
            {
                return this.side_involvementField;
            }
            set
            {
                this.side_involvementField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("side_citizen", typeof(SideTypeSide_citizen))]
        [System.Xml.Serialization.XmlElementAttribute("side_firm", typeof(SideTypeSide_firm))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SideTypeSide_citizen
    {

        private string side_name_1Field;

        private string side_renameField;

        private string side_family_1Field;

        private string side_family_2Field;

        private string side_egnField;

        /// <remarks/>
        public string side_name_1
        {
            get
            {
                return this.side_name_1Field;
            }
            set
            {
                this.side_name_1Field = value;
            }
        }

        /// <remarks/>
        public string side_rename
        {
            get
            {
                return this.side_renameField;
            }
            set
            {
                this.side_renameField = value;
            }
        }

        /// <remarks/>
        public string side_family_1
        {
            get
            {
                return this.side_family_1Field;
            }
            set
            {
                this.side_family_1Field = value;
            }
        }

        /// <remarks/>
        public string side_family_2
        {
            get
            {
                return this.side_family_2Field;
            }
            set
            {
                this.side_family_2Field = value;
            }
        }

        /// <remarks/>
        public string side_egn
        {
            get
            {
                return this.side_egnField;
            }
            set
            {
                this.side_egnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SideTypeSide_firm
    {

        private string side_nameField;

        private string side_bulstatField;

        /// <remarks/>
        public string side_name
        {
            get
            {
                return this.side_nameField;
            }
            set
            {
                this.side_nameField = value;
            }
        }

        /// <remarks/>
        public string side_bulstat
        {
            get
            {
                return this.side_bulstatField;
            }
            set
            {
                this.side_bulstatField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActType
    {

        private ExtensionsType extensionsField;

        private string act_idField;

        private int act_actionField;

        private int act_kindField;

        private int act_noField;

        private bool act_noFieldSpecified;

        private System.DateTime act_dateField;

        private int[] act_reasonField;

        private int act_debtor_statusField;

        private bool act_debtor_statusFieldSpecified;

        private string act_textField;

        private byte[] act_imageField;

        private AppealType[] appealField;

        /// <remarks/>
        public ExtensionsType extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }

        /// <remarks/>
        public string act_id
        {
            get
            {
                return this.act_idField;
            }
            set
            {
                this.act_idField = value;
            }
        }

        /// <remarks/>
        public int act_action
        {
            get
            {
                return this.act_actionField;
            }
            set
            {
                this.act_actionField = value;
            }
        }

        /// <remarks/>
        public int act_kind
        {
            get
            {
                return this.act_kindField;
            }
            set
            {
                this.act_kindField = value;
            }
        }

        /// <remarks/>
        public int act_no
        {
            get
            {
                return this.act_noField;
            }
            set
            {
                this.act_noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool act_noSpecified
        {
            get
            {
                return this.act_noFieldSpecified;
            }
            set
            {
                this.act_noFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime act_date
        {
            get
            {
                return this.act_dateField;
            }
            set
            {
                this.act_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("act_reason")]
        public int[] act_reason
        {
            get
            {
                return this.act_reasonField;
            }
            set
            {
                this.act_reasonField = value;
            }
        }

        /// <remarks/>
        public int act_debtor_status
        {
            get
            {
                return this.act_debtor_statusField;
            }
            set
            {
                this.act_debtor_statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool act_debtor_statusSpecified
        {
            get
            {
                return this.act_debtor_statusFieldSpecified;
            }
            set
            {
                this.act_debtor_statusFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string act_text
        {
            get
            {
                return this.act_textField;
            }
            set
            {
                this.act_textField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] act_image
        {
            get
            {
                return this.act_imageField;
            }
            set
            {
                this.act_imageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Appeal")]
        public AppealType[] Appeal
        {
            get
            {
                return this.appealField;
            }
            set
            {
                this.appealField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SurroundProcessedType
    {

        private ExtensionsType extensionsField;

        private string surround_idField;

        private int surround_noField;

        private string surround_yearField;

        /// <remarks/>
        public ExtensionsType extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }

        /// <remarks/>
        public string surround_id
        {
            get
            {
                return this.surround_idField;
            }
            set
            {
                this.surround_idField = value;
            }
        }

        /// <remarks/>
        public int surround_no
        {
            get
            {
                return this.surround_noField;
            }
            set
            {
                this.surround_noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "gYear")]
        public string surround_year
        {
            get
            {
                return this.surround_yearField;
            }
            set
            {
                this.surround_yearField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JudgeType
    {

        private ExtensionsType extensionsField;

        private string judge_idField;

        private string judge_name_1Field;

        private string judge_renameField;

        private string judge_family_1Field;

        private string judge_family_2Field;

        private string judge_egnField;

        /// <remarks/>
        public ExtensionsType extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }

        /// <remarks/>
        public string judge_id
        {
            get
            {
                return this.judge_idField;
            }
            set
            {
                this.judge_idField = value;
            }
        }

        /// <remarks/>
        public string judge_name_1
        {
            get
            {
                return this.judge_name_1Field;
            }
            set
            {
                this.judge_name_1Field = value;
            }
        }

        /// <remarks/>
        public string judge_rename
        {
            get
            {
                return this.judge_renameField;
            }
            set
            {
                this.judge_renameField = value;
            }
        }

        /// <remarks/>
        public string judge_family_1
        {
            get
            {
                return this.judge_family_1Field;
            }
            set
            {
                this.judge_family_1Field = value;
            }
        }

        /// <remarks/>
        public string judge_family_2
        {
            get
            {
                return this.judge_family_2Field;
            }
            set
            {
                this.judge_family_2Field = value;
            }
        }

        /// <remarks/>
        public string judge_egn
        {
            get
            {
                return this.judge_egnField;
            }
            set
            {
                this.judge_egnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SessionType
    {

        private ExtensionsType extensionsField;

        private string session_idField;

        private int session_actionField;

        private int session_kindField;

        private System.DateTime session_dateField;

        private System.DateTime session_timeField;

        private bool session_timeFieldSpecified;

        private int session_resultField;

        private string session_textField;

        private JudgeType[] judgeField;

        private SurroundProcessedType[] surroundField;

        private ActType[] actField;

        /// <remarks/>
        public ExtensionsType extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }

        /// <remarks/>
        public string session_id
        {
            get
            {
                return this.session_idField;
            }
            set
            {
                this.session_idField = value;
            }
        }

        /// <remarks/>
        public int session_action
        {
            get
            {
                return this.session_actionField;
            }
            set
            {
                this.session_actionField = value;
            }
        }

        /// <remarks/>
        public int session_kind
        {
            get
            {
                return this.session_kindField;
            }
            set
            {
                this.session_kindField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime session_date
        {
            get
            {
                return this.session_dateField;
            }
            set
            {
                this.session_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
        public System.DateTime session_time
        {
            get
            {
                return this.session_timeField;
            }
            set
            {
                this.session_timeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool session_timeSpecified
        {
            get
            {
                return this.session_timeFieldSpecified;
            }
            set
            {
                this.session_timeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int session_result
        {
            get
            {
                return this.session_resultField;
            }
            set
            {
                this.session_resultField = value;
            }
        }

        /// <remarks/>
        public string session_text
        {
            get
            {
                return this.session_textField;
            }
            set
            {
                this.session_textField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Judge")]
        public JudgeType[] Judge
        {
            get
            {
                return this.judgeField;
            }
            set
            {
                this.judgeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Surround")]
        public SurroundProcessedType[] Surround
        {
            get
            {
                return this.surroundField;
            }
            set
            {
                this.surroundField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Act")]
        public ActType[] Act
        {
            get
            {
                return this.actField;
            }
            set
            {
                this.actField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SurroundType
    {

        private ExtensionsType extensionsField;

        private string surround_idField;

        private int surround_actionField;

        private int surround_noField;

        private string surround_yearField;

        private System.DateTime surround_dateField;

        private string surround_textField;

        private SideType[] sideField;

        /// <remarks/>
        public ExtensionsType extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }

        /// <remarks/>
        public string surround_id
        {
            get
            {
                return this.surround_idField;
            }
            set
            {
                this.surround_idField = value;
            }
        }

        /// <remarks/>
        public int surround_action
        {
            get
            {
                return this.surround_actionField;
            }
            set
            {
                this.surround_actionField = value;
            }
        }

        /// <remarks/>
        public int surround_no
        {
            get
            {
                return this.surround_noField;
            }
            set
            {
                this.surround_noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "gYear")]
        public string surround_year
        {
            get
            {
                return this.surround_yearField;
            }
            set
            {
                this.surround_yearField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime surround_date
        {
            get
            {
                return this.surround_dateField;
            }
            set
            {
                this.surround_dateField = value;
            }
        }

        /// <remarks/>
        public string surround_text
        {
            get
            {
                return this.surround_textField;
            }
            set
            {
                this.surround_textField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Side")]
        public SideType[] Side
        {
            get
            {
                return this.sideField;
            }
            set
            {
                this.sideField = value;
            }
        }
    }
}
