//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integration.LegalActs
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Act", Namespace="http://schemas.datacontract.org/2004/07/LegalActsDataEntities")]
    public partial class Act : object
    {
        
        private int ActKindField;
        
        private byte[] ActTextField;
        
        private string ActTextTypeField;
        
        private int CaseKindField;
        
        private int CaseNumberField;
        
        private Integration.LegalActs.ConnectedCaseBase[] ConnectedCasesField;
        
        private int CourtField;
        
        private Integration.LegalActs.DataForHigherCourt DataForHigherCourtField;
        
        private string EcliCodeField;
        
        private string JudgeField;
        
        private System.Nullable<System.DateTime> LegalDateField;
        
        private System.Nullable<System.DateTime> MotiveDateField;
        
        private byte[] MotiveTextField;
        
        private string MotiveTextTypeField;
        
        private System.Nullable<int> NumberField;
        
        private string PreviousEcliCodeField;
        
        private string ResultOfAppealField;
        
        private System.Nullable<System.DateTime> StartDateField;
        
        private string UIDField;
        
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActKind
        {
            get
            {
                return this.ActKindField;
            }
            set
            {
                this.ActKindField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ActText
        {
            get
            {
                return this.ActTextField;
            }
            set
            {
                this.ActTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActTextType
        {
            get
            {
                return this.ActTextTypeField;
            }
            set
            {
                this.ActTextTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CaseKind
        {
            get
            {
                return this.CaseKindField;
            }
            set
            {
                this.CaseKindField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CaseNumber
        {
            get
            {
                return this.CaseNumberField;
            }
            set
            {
                this.CaseNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Integration.LegalActs.ConnectedCaseBase[] ConnectedCases
        {
            get
            {
                return this.ConnectedCasesField;
            }
            set
            {
                this.ConnectedCasesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Court
        {
            get
            {
                return this.CourtField;
            }
            set
            {
                this.CourtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Integration.LegalActs.DataForHigherCourt DataForHigherCourt
        {
            get
            {
                return this.DataForHigherCourtField;
            }
            set
            {
                this.DataForHigherCourtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EcliCode
        {
            get
            {
                return this.EcliCodeField;
            }
            set
            {
                this.EcliCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Judge
        {
            get
            {
                return this.JudgeField;
            }
            set
            {
                this.JudgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LegalDate
        {
            get
            {
                return this.LegalDateField;
            }
            set
            {
                this.LegalDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MotiveDate
        {
            get
            {
                return this.MotiveDateField;
            }
            set
            {
                this.MotiveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] MotiveText
        {
            get
            {
                return this.MotiveTextField;
            }
            set
            {
                this.MotiveTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotiveTextType
        {
            get
            {
                return this.MotiveTextTypeField;
            }
            set
            {
                this.MotiveTextTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreviousEcliCode
        {
            get
            {
                return this.PreviousEcliCodeField;
            }
            set
            {
                this.PreviousEcliCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultOfAppeal
        {
            get
            {
                return this.ResultOfAppealField;
            }
            set
            {
                this.ResultOfAppealField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UID
        {
            get
            {
                return this.UIDField;
            }
            set
            {
                this.UIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataForHigherCourt", Namespace="http://schemas.datacontract.org/2004/07/LegalActsDataEntities")]
    public partial class DataForHigherCourt : object
    {
        
        private int CourtField;
        
        private System.Nullable<System.DateTime> DateOfDispatchField;
        
        private int OutputNumberField;
        
        private int TypeOfDocumentField;
        
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Court
        {
            get
            {
                return this.CourtField;
            }
            set
            {
                this.CourtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfDispatch
        {
            get
            {
                return this.DateOfDispatchField;
            }
            set
            {
                this.DateOfDispatchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OutputNumber
        {
            get
            {
                return this.OutputNumberField;
            }
            set
            {
                this.OutputNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeOfDocument
        {
            get
            {
                return this.TypeOfDocumentField;
            }
            set
            {
                this.TypeOfDocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectedCaseBase", Namespace="http://schemas.datacontract.org/2004/07/LegalActsDataEntities")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Integration.LegalActs.LevelOneCase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Integration.LegalActs.LevelTwoCase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Integration.LegalActs.LevelThreeCase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Integration.LegalActs.JurisdictionCase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Integration.LegalActs.ReturnCase))]
    public partial class ConnectedCaseBase : object
    {
        
        private int CaseKindField;
        
        private int ConnectTypeField;
        
        private int CourtField;
        
        private int NumberField;
        
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CaseKind
        {
            get
            {
                return this.CaseKindField;
            }
            set
            {
                this.CaseKindField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConnectType
        {
            get
            {
                return this.ConnectTypeField;
            }
            set
            {
                this.ConnectTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Court
        {
            get
            {
                return this.CourtField;
            }
            set
            {
                this.CourtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LevelOneCase", Namespace="http://schemas.datacontract.org/2004/07/LegalActsDataEntities")]
    public partial class LevelOneCase : Integration.LegalActs.ConnectedCaseBase
    {
        
        private System.Nullable<System.DateTime> DateOfAppealActField;
        
        private System.Nullable<int> NumberOfAppealActField;
        
        private int TypeOfAppealActField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfAppealAct
        {
            get
            {
                return this.DateOfAppealActField;
            }
            set
            {
                this.DateOfAppealActField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumberOfAppealAct
        {
            get
            {
                return this.NumberOfAppealActField;
            }
            set
            {
                this.NumberOfAppealActField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeOfAppealAct
        {
            get
            {
                return this.TypeOfAppealActField;
            }
            set
            {
                this.TypeOfAppealActField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LevelTwoCase", Namespace="http://schemas.datacontract.org/2004/07/LegalActsDataEntities")]
    public partial class LevelTwoCase : Integration.LegalActs.ConnectedCaseBase
    {
        
        private System.Nullable<System.DateTime> DateOfAppealActField;
        
        private System.Nullable<int> NumberOfAppealActField;
        
        private int TypeOfAppealActField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfAppealAct
        {
            get
            {
                return this.DateOfAppealActField;
            }
            set
            {
                this.DateOfAppealActField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumberOfAppealAct
        {
            get
            {
                return this.NumberOfAppealActField;
            }
            set
            {
                this.NumberOfAppealActField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeOfAppealAct
        {
            get
            {
                return this.TypeOfAppealActField;
            }
            set
            {
                this.TypeOfAppealActField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LevelThreeCase", Namespace="http://schemas.datacontract.org/2004/07/LegalActsDataEntities")]
    public partial class LevelThreeCase : Integration.LegalActs.ConnectedCaseBase
    {
        
        private System.Nullable<int> NumberOfAppealActField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumberOfAppealAct
        {
            get
            {
                return this.NumberOfAppealActField;
            }
            set
            {
                this.NumberOfAppealActField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JurisdictionCase", Namespace="http://schemas.datacontract.org/2004/07/LegalActsDataEntities")]
    public partial class JurisdictionCase : Integration.LegalActs.ConnectedCaseBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnCase", Namespace="http://schemas.datacontract.org/2004/07/LegalActsDataEntities")]
    public partial class ReturnCase : Integration.LegalActs.ConnectedCaseBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LegalActFault", Namespace="http://www.vss.justice.bg/LegalActs")]
    public partial class LegalActFault : object
    {
        
        private int ErrorCodeField;
        
        private string ErrorFieldField;
        
        private string ReasonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorField
        {
            get
            {
                return this.ErrorFieldField;
            }
            set
            {
                this.ErrorFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.vss.justice.bg/LegalActs", ConfigurationName="Integration.LegalActs.ILegalActsService")]
    public interface ILegalActsService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vss.justice.bg/LegalActs/ILegalActsService/SendAct", ReplyAction="http://www.vss.justice.bg/LegalActs/ILegalActsService/SendActResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Integration.LegalActs.LegalActFault), Action="http://www.vss.justice.bg/LegalActs/ILegalActsService/SendActLegalActFaultFault", Name="LegalActFault")]
        void SendAct(Integration.LegalActs.Act act);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vss.justice.bg/LegalActs/ILegalActsService/SendAct", ReplyAction="http://www.vss.justice.bg/LegalActs/ILegalActsService/SendActResponse")]
        System.Threading.Tasks.Task SendActAsync(Integration.LegalActs.Act act);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vss.justice.bg/LegalActs/ILegalActsService/DeleteAct", ReplyAction="http://www.vss.justice.bg/LegalActs/ILegalActsService/DeleteActResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Integration.LegalActs.LegalActFault), Action="http://www.vss.justice.bg/LegalActs/ILegalActsService/DeleteActLegalActFaultFault" +
            "", Name="LegalActFault")]
        void DeleteAct(Integration.LegalActs.Act act);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vss.justice.bg/LegalActs/ILegalActsService/DeleteAct", ReplyAction="http://www.vss.justice.bg/LegalActs/ILegalActsService/DeleteActResponse")]
        System.Threading.Tasks.Task DeleteActAsync(Integration.LegalActs.Act act);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ILegalActsServiceChannel : Integration.LegalActs.ILegalActsService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class LegalActsServiceClient : System.ServiceModel.ClientBase<Integration.LegalActs.ILegalActsService>, Integration.LegalActs.ILegalActsService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LegalActsServiceClient() : 
                base(LegalActsServiceClient.GetDefaultBinding(), LegalActsServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ILegalActsService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LegalActsServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(LegalActsServiceClient.GetBindingForEndpoint(endpointConfiguration), LegalActsServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LegalActsServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LegalActsServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LegalActsServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LegalActsServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LegalActsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void SendAct(Integration.LegalActs.Act act)
        {
            base.Channel.SendAct(act);
        }
        
        public System.Threading.Tasks.Task SendActAsync(Integration.LegalActs.Act act)
        {
            return base.Channel.SendActAsync(act);
        }
        
        public void DeleteAct(Integration.LegalActs.Act act)
        {
            base.Channel.DeleteAct(act);
        }
        
        public System.Threading.Tasks.Task DeleteActAsync(Integration.LegalActs.Act act)
        {
            return base.Channel.DeleteActAsync(act);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILegalActsService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILegalActsService))
            {
                return new System.ServiceModel.EndpointAddress("http://servicelegalacts.abbaty.com/LegalActsWebService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LegalActsServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ILegalActsService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LegalActsServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ILegalActsService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ILegalActsService,
        }
    }
}
