//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Integration.Eispp
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://IntegrationService.Eispp", ConfigurationName="Integration.Eispp.IEisppService")]
    public interface IEisppService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationService.Eispp/IEisppService/SendMessage", ReplyAction="http://IntegrationService.Eispp/IEisppService/SendMessageResponse")]
        System.Threading.Tasks.Task<bool> SendMessageAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationService.Eispp/IEisppService/ReceiveMessages", ReplyAction="http://IntegrationService.Eispp/IEisppService/ReceiveMessagesResponse")]
        System.Threading.Tasks.Task<string[]> ReceiveMessagesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IEisppServiceChannel : Integration.Eispp.IEisppService, System.ServiceModel.IClientChannel
    {
    }
    
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class EisppServiceClient : System.ServiceModel.ClientBase<Integration.Eispp.IEisppService>, Integration.Eispp.IEisppService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EisppServiceClient() : 
                base(EisppServiceClient.GetDefaultBinding(), EisppServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IEisppService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EisppServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(EisppServiceClient.GetBindingForEndpoint(endpointConfiguration), EisppServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EisppServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EisppServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EisppServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EisppServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EisppServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> SendMessageAsync(string message)
        {
            return base.Channel.SendMessageAsync(message);
        }
        
        public System.Threading.Tasks.Task<string[]> ReceiveMessagesAsync()
        {
            return base.Channel.ReceiveMessagesAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEisppService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEisppService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8000/EisppService/service");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EisppServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IEisppService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EisppServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IEisppService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IEisppService,
        }
    }
}
